"""Windows rule set - CIS-style benchmark checks (read-only).

Each rule is evaluated read-only via registry / PowerShell / service probes.
Rule IDs use the HC- prefix (Hardening Check) to stay benchmark-neutral while
mirroring common CIS Microsoft Windows recommendations.
"""

from __future__ import annotations

from hardening_checker.core.models import Profile, Remediation, Rule, Severity

W = "windows"


def _r(
    rule_id, title, severity, category, spec, *, description="", rationale="",
    remediation_summary="", steps=None, script="", profile=Profile.L1,
    requires_admin=False, manual=False, refs=None, tags=None, audit_hint="",
):
    return Rule(
        rule_id=rule_id,
        title=title,
        description=description or title,
        severity=severity,
        profile=profile,
        category=category,
        check_spec=spec,
        remediation=Remediation(
            summary=remediation_summary or title,
            steps=steps or [],
            script=script,
            script_shell="powershell" if script else "",
        ),
        rationale=rationale,
        refs=refs or [],
        requires_admin=requires_admin,
        manual=manual,
        platforms=(W,),
        tags=tags or [],
        audit_hint=audit_hint,
    )


def get_rules() -> list[Rule]:
    rules: list[Rule] = []

    # ------------------------------------------------------ Account policies
    rules += [
        _r(
            "HC-WIN-0001", "Minimum password length is 14 or more characters",
            Severity.HIGH, "Account Policies",
            {"kind": "command", "capture": "stdout",
             "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Minimum password length\s*:?\s*14",
             "fail_message": "Minimum password length is below 14 characters.",
             "audit_hint": "net accounts lists the effective local password policy."},
            description="Enforce passwords of at least 14 characters.",
            rationale="Longer passwords resist offline cracking and brute force.",
            remediation_summary="Raise minimum password length to 14.",
            steps=["Open 'secpol.msc' > Account Policies > Password Policy.",
                   "Set 'Minimum password length' to 14 or more."],
            script="net accounts /minpwlen:14",
            refs=["CIS 1.1.1 (L1)"],
        ),
        _r(
            "HC-WIN-0002", "Password history is 24 passwords remembered",
            Severity.MEDIUM, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Password history length\s*:?\s*24",
             "fail_message": "Password history is below 24.",
             "audit_hint": "Prevents reuse of recent passwords."},
            remediation_summary="Set password history to 24.",
            script="net accounts /uniquepw:24",
            refs=["CIS 1.1.2 (L1)"],
        ),
        _r(
            "HC-WIN-0003", "Maximum password age is 365 days or fewer",
            Severity.MEDIUM, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Maximum password age \(days\)\s*:?\s*(?:\d{1,2}|[1-2]\d{2}|3[0-5]\d|360)",
             "fail_message": "Maximum password age exceeds 365 days.",
             "audit_hint": "Ages above 365 days let stale passwords persist."},
            remediation_summary="Set maximum password age to 365 or fewer (non-zero).",
            script="net accounts /maxpwage:90",
            refs=["CIS 1.1.3 (L1)"],
        ),
        _r(
            "HC-WIN-0004", "Minimum password age is 1 day or more",
            Severity.LOW, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Minimum password age \(days\)\s*:?\s*[1-9]",
             "fail_message": "Minimum password age is 0 (users can immediately cycle passwords).",
             "audit_hint": "Prevents users from instantly reusing old passwords."},
            remediation_summary="Set minimum password age to at least 1 day.",
            script="net accounts /minpwage:1",
            refs=["CIS 1.1.4 (L1)"],
        ),
        _r(
            "HC-WIN-0005", "Password complexity is enabled",
            Severity.HIGH, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Password complexity\s*:?\s*(?:Enabled|Yes)",
             "fail_message": "Password complexity is disabled.",
             "audit_hint": "Complexity requirements force mixed character classes."},
            remediation_summary="Enable password complexity requirements.",
            script="secedit /export /cfg %TEMP%\\secedit.inf; (Get-Content %TEMP%\\secedit.inf) -replace 'PasswordComplexity = 0','PasswordComplexity = 1' | Set-Content %TEMP%\\secedit.inf; secedit /configure /db secedit.sdb /cfg %TEMP%\\secedit.inf",
            refs=["CIS 1.1.5 (L1)"],
        ),
        _r(
            "HC-WIN-0006", "Account lockout threshold is 5 or fewer",
            Severity.MEDIUM, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Lockout threshold\s*:?\s*[0-5]\b",
             "fail_message": "Lockout threshold is above 5 attempts.",
             "audit_hint": "Lower thresholds slow online brute force."},
            remediation_summary="Set account lockout threshold to 5 or fewer.",
            script="net accounts /lockoutthreshold:5",
            refs=["CIS 1.2.1 (L1)"],
        ),
        _r(
            "HC-WIN-0007", "Account lockout duration is 15 minutes or more",
            Severity.LOW, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Lockout duration \(minutes\)\s*:?\s*(?:1[5-9]|[2-9]\d|\d{3,})",
             "fail_message": "Lockout duration is below 15 minutes.",
             "audit_hint": "Longer lockouts increase brute-force cost."},
            remediation_summary="Set lockout duration to at least 15 minutes.",
            script="net accounts /lockoutduration:15",
            refs=["CIS 1.2.2 (L1)"],
        ),
        _r(
            "HC-WIN-0008", "Reset account lockout counter is 15 minutes or more",
            Severity.LOW, "Account Policies",
            {"kind": "command", "capture": "stdout", "command": ["net", "accounts"],
             "expected_kind": "regex",
             "expected": r"Lockout observation window \(minutes\)\s*:?\s*(?:1[5-9]|[2-9]\d|\d{3,})",
             "fail_message": "Lockout counter reset window is below 15 minutes.",
             "audit_hint": "Counter window should match lockout duration."},
            remediation_summary="Set lockout counter reset to 15 minutes or more.",
            script="net accounts /lockoutwindow:15",
            refs=["CIS 1.2.3 (L1)"],
        ),
    ]

    # ------------------------------------------------------------ UAC / LSA
    rules += [
        _r(
            "HC-WIN-0101", "UAC: Admin Approval Mode for built-in Administrator",
            Severity.CRITICAL, "User Account Control",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "value": "FilterAdministratorToken",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "Built-in Administrator does not run with UAC Admin Approval Mode.",
             "audit_hint": "FilterAdministratorToken=1 forces the built-in admin through UAC."},
            remediation_summary="Enable Admin Approval Mode for the built-in Administrator.",
            steps=["gpedit.msc > Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options.",
                   "Set 'User Account Control: Admin Approval Mode for the Built-in Administrator account' to Enabled."],
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name FilterAdministratorToken -Value 1",
            refs=["CIS 2.3.17.1 (L1)"],
        ),
        _r(
            "HC-WIN-0102", "UAC: elevation prompt for standard users",
            Severity.HIGH, "User Account Control",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "value": "ConsentPromptBehaviorUser",
             "expected_kind": "one_of", "options": ["0", "3"],
             "fail_message": "Standard users are auto-denied or over-permitted on elevation.",
             "audit_hint": "0=auto-deny, 3=credentials prompt. 1,2 are non-compliant."},
            remediation_summary="Configure UAC prompt behavior for standard users.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name ConsentPromptBehaviorUser -Value 3",
            refs=["CIS 2.3.17.2 (L1)"],
        ),
        _r(
            "HC-WIN-0103", "UAC: secure desktop on elevation prompt",
            Severity.MEDIUM, "User Account Control",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "value": "PromptOnSecureDesktop",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "Elevation prompt is not on the secure desktop.",
             "audit_hint": "Secure desktop isolates the UAC prompt from desktop shims."},
            remediation_summary="Enable secure desktop for elevation prompts.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name PromptOnSecureDesktop -Value 1",
            refs=["CIS 2.3.17.5 (L1)"],
        ),
        _r(
            "HC-WIN-0104", "UAC: elevation prompt for admins is not 'never notify'",
            Severity.CRITICAL, "User Account Control",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "value": "ConsentPromptBehaviorAdmin",
             "expected_kind": "one_of", "options": ["1", "2", "5"],
             "fail_message": "Admin elevation is silent (never notify).",
             "audit_hint": "0 = silent elevation. 1,2,5 require interaction."},
            remediation_summary="Require an elevation prompt for admins.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name ConsentPromptBehaviorAdmin -Value 5",
            refs=["CIS 2.3.17.4 (L1)"],
        ),
        _r(
            "HC-WIN-0105", "LSA Protection is enabled (RunAsPPL)",
            Severity.CRITICAL, "LSA Protection",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
             "value": "RunAsPPL",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "LSA runs unprotected (credential dumping risk).",
             "audit_hint": "RunAsPPL=1 runs LSASS as a protected process."},
            remediation_summary="Enable LSA Protection.",
            steps=["Run 'regedit' as admin.",
                   "Set HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\RunAsPPL = 1 (DWORD)."],
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RunAsPPL -Type DWord -Value 1",
            refs=["CIS 2.3.11.1 (L1)"],
        ),
        _r(
            "HC-WIN-0106", "LSA: NTLMv2 only, LM refused",
            Severity.HIGH, "LSA Protection",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
             "value": "LmCompatibilityLevel",
             "expected_kind": "exact", "expected": 5,
             "fail_message": "LM/NTLMv1 may still be negotiated.",
             "audit_hint": "Level 5 sends NTLMv2 only and refuses LM/NTLM."},
            remediation_summary="Set LM compatibility level to 5 (NTLMv2 only).",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LmCompatibilityLevel -Type DWord -Value 5",
            refs=["CIS 2.3.11.4 (L1)"],
        ),
        _r(
            "HC-WIN-0107", "NTLM session security: minimum 128-bit",
            Severity.MEDIUM, "LSA Protection",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0",
             "value": "NtlmMinClientSec",
             "expected_kind": "min", "expected": 537395200,
             "fail_message": "NTLM minimum security is below 128-bit + signing/sealing.",
             "audit_hint": "0x20080000 = Require NTLMv2 session security + 128-bit."},
            remediation_summary="Raise NTLM minimum client security to 0x20080000.",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0' -Name NtlmMinClientSec -Type DWord -Value 537395200",
            refs=["CIS 2.3.11.7 (L1)"],
        ),
    ]

    # ------------------------------------------------------------- BitLocker
    rules += [
        _r(
            "HC-WIN-0201", "BitLocker: OS volume protection is on",
            Severity.CRITICAL, "BitLocker",
            {"kind": "powershell",
             "script": "(Get-BitLockerVolume -MountPoint $env:SystemDrive).ProtectionStatus -eq 'On'",
             "as_bool": True,
             "expected_kind": "equals_bool", "expected": True,
             "fail_message": "The OS volume is not protected by BitLocker.",
             "audit_hint": "Get-BitLockerVolume reports per-volume protection."},
            remediation_summary="Enable BitLocker on the OS volume.",
            steps=["Control Panel > BitLocker Drive Encryption > Turn on BitLocker.",
                   "Or run: Enable-BitLocker -MountPoint $env:SystemDrive -UsedSpaceOnly -SkipHardwareTest"],
            requires_admin=True,
            refs=["CIS BitLocker (L2)"],
            tags=["encryption"],
        ),
        _r(
            "HC-WIN-0202", "BitLocker: recovery info escrowed to AD/AAD",
            Severity.HIGH, "BitLocker",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\FVE",
             "value": "ActiveDirectoryBackup",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "BitLocker recovery keys are not backed up to AD/AAD.",
             "audit_hint": "ActiveDirectoryBackup=1 escrows recovery keys centrally."},
            remediation_summary="Enable BitLocker recovery key escrow.",
            script="Add-Type -AssemblyName Policy.OM.Client; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE' -Name ActiveDirectoryBackup -Type DWord -Value 1",
            requires_admin=True,
            refs=["CIS BitLocker (L2)"],
            tags=["encryption"],
        ),
    ]

    # ------------------------------------------------------- Defender / AV
    rules += [
        _r(
            "HC-WIN-0301", "Windows Defender real-time protection is on",
            Severity.CRITICAL, "Windows Defender",
            {"kind": "powershell",
             "script": "(Get-MpComputerStatus).RealTimeProtectionEnabled",
             "as_bool": True,
             "expected_kind": "equals_bool", "expected": True,
             "fail_message": "Real-time protection is off.",
             "audit_hint": "Get-MpComputerStatus exposes Defender runtime state."},
            remediation_summary="Enable Defender real-time protection.",
            script="Set-MpPreference -DisableRealtimeMonitoring $false",
            refs=["CIS 18.9.47 (L1)"],
        ),
        _r(
            "HC-WIN-0302", "Defender behavior monitoring is on",
            Severity.MEDIUM, "Windows Defender",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows Defender",
             "value": "DisableBehaviorMonitoring",
             "expected_kind": "exact", "expected": 0,
             "fail_message": "Defender behavior monitoring is disabled by policy.",
             "audit_hint": "DisableBehaviorMonitoring=0 keeps behavior monitoring on."},
            remediation_summary="Keep Defender behavior monitoring enabled.",
            script="Remove-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender' -Name DisableBehaviorMonitoring -ErrorAction SilentlyContinue",
            refs=["CIS 18.9.47 (L1)"],
        ),
        _r(
            "HC-WIN-0303", "Defender signature updates are recent (7 days)",
            Severity.HIGH, "Windows Defender",
            {"kind": "powershell",
             "script": "((Get-Date) - (Get-MpComputerStatus).AntivirusSignatureLastUpdated).TotalDays",
             "as_float": True,
             "expected_kind": "max", "expected": 7,
             "fail_message": "Defender signatures are older than 7 days.",
             "audit_hint": "Stale signatures leave the host blind to new threats."},
            remediation_summary="Update Defender signatures.",
            script="Update-MpSignature",
            refs=["CIS 18.9.47 (L1)"],
        ),
        _r(
            "HC-WIN-0304", "Tamper Protection is on",
            Severity.HIGH, "Windows Defender",
            {"kind": "powershell",
             "script": "(Get-MpComputerStatus).IsTamperProtected",
             "as_bool": True,
             "expected_kind": "equals_bool", "expected": True,
             "fail_message": "Tamper Protection is off.",
             "audit_hint": "Tamper Protection blocks Defender config changes."},
            remediation_summary="Enable Tamper Protection.",
            steps=["Windows Security > Virus & threat protection > Manage settings > Tamper Protection = On."],
            refs=["CIS 18.9.47 (L1)"],
        ),
    ]

    # ------------------------------------------------------------- Firewall
    rules += [
        _r(
            "HC-WIN-0401", "Domain profile firewall is on",
            Severity.HIGH, "Firewall",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile",
             "value": "EnableFirewall",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Domain profile firewall is off.",
             "audit_hint": "Missing value means default-on; explicit 0 is non-compliant."},
            remediation_summary="Enable the domain firewall profile.",
            script="Set-NetFirewallProfile -Profile Domain -Enabled True",
            refs=["CIS 9.1.1 (L1)"],
        ),
        _r(
            "HC-WIN-0402", "Private profile firewall is on",
            Severity.HIGH, "Firewall",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile",
             "value": "EnableFirewall",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Private profile firewall is off.",
             "audit_hint": "Private networks still need host firewall."},
            remediation_summary="Enable the private firewall profile.",
            script="Set-NetFirewallProfile -Profile Private -Enabled True",
            refs=["CIS 9.1.2 (L1)"],
        ),
        _r(
            "HC-WIN-0403", "Public profile firewall is on",
            Severity.HIGH, "Firewall",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile",
             "value": "EnableFirewall",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Public profile firewall is off.",
             "audit_hint": "Public profile is the highest-risk network."},
            remediation_summary="Enable the public firewall profile.",
            script="Set-NetFirewallProfile -Profile Public -Enabled True",
            refs=["CIS 9.1.3 (L1)"],
        ),
        _r(
            "HC-WIN-0404", "Firewall blocks inbound by default (public)",
            Severity.MEDIUM, "Firewall",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile",
             "value": "DefaultInboundAction",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Public inbound default is not Block.",
             "audit_hint": "DefaultInboundAction 1=Block 2=Allow (policy value)."},
            remediation_summary="Set public inbound default to Block.",
            script="Set-NetFirewallProfile -Profile Public -DefaultInboundAction Block",
            refs=["CIS 9.1.4 (L1)"],
        ),
        _r(
            "HC-WIN-0405", "Firewall logs dropped packets (public)",
            Severity.LOW, "Firewall",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging",
             "value": "LogDroppedPackets",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Dropped packets are not logged for the public profile.",
             "audit_hint": "LogDroppedPackets=1 enables drop logging."},
            remediation_summary="Enable dropped-packet logging.",
            script="Set-NetFirewallProfile -Profile Public -LogDroppedPackets True",
            refs=["CIS 9.1.5 (L1)"],
        ),
    ]

    # ------------------------------------------------------------------ RDP
    rules += [
        _r(
            "HC-WIN-0501", "RDP: NLA required",
            Severity.HIGH, "Remote Desktop",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp",
             "value": "UserAuthentication",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "RDP does not require Network Level Authentication.",
             "audit_hint": "NLA blocks unauthenticated pre-auth sessions."},
            remediation_summary="Require NLA for RDP.",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name UserAuthentication -Type DWord -Value 1",
            refs=["CIS 18.9.65 (L1)"],
        ),
        _r(
            "HC-WIN-0502", "RDP: encryption level is high",
            Severity.MEDIUM, "Remote Desktop",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp",
             "value": "MinEncryptionLevel",
             "expected_kind": "exact", "expected": 3,
             "fail_message": "RDP encryption is below High.",
             "audit_hint": "3 = High: client/server data encrypted end to end."},
            remediation_summary="Set RDP encryption to High.",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name MinEncryptionLevel -Type DWord -Value 3",
            refs=["CIS 18.9.65 (L1)"],
        ),
        _r(
            "HC-WIN-0503", "RDP: session timeout for disconnected sessions",
            Severity.LOW, "Remote Desktop",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services",
             "value": "MaxDisconnectionTime",
             "expected_kind": "min", "expected": 1,
             "allow_missing": True,
             "fail_message": "Disconnected RDP sessions are never reaped.",
             "audit_hint": "MaxDisconnectionTime (ms) > 0 enforces idle cleanup."},
            remediation_summary="Configure a disconnect timeout for RDP sessions.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MaxDisconnectionTime -Type DWord -Value 28800000",
            refs=["CIS 18.9.65 (L1)"],
        ),
    ]

    # ------------------------------------------------------------- Auditing
    rules += [
        _r(
            "HC-WIN-0601", "Audit: account logon failure events enabled",
            Severity.MEDIUM, "Audit Policy",
            {"kind": "command", "capture": "stdout",
             "command": ["auditpol", "/get", "/category:*"],
             "expected_kind": "regex",
             "expected": r"Credential Validation\s+\S*\s*Failure",
             "fail_message": "Credential Validation failure auditing is off.",
             "audit_hint": "auditpol shows the effective per-user audit policy."},
            remediation_summary="Enable Credential Validation failure auditing.",
            script="auditpol /set /subcategory:'Credential Validation' /failure:enable",
            refs=["CIS 17.x (L1)"],
        ),
        _r(
            "HC-WIN-0602", "Audit: logon failure events enabled",
            Severity.MEDIUM, "Audit Policy",
            {"kind": "command", "capture": "stdout",
             "command": ["auditpol", "/get", "/category:*"],
             "expected_kind": "regex",
             "expected": r"Logon\s+\S*\s*Failure",
             "fail_message": "Logon failure auditing is off.",
             "audit_hint": "Logon failure events are core detection telemetry."},
            remediation_summary="Enable Logon failure auditing.",
            script="auditpol /set /subcategory:'Logoff'; auditpol /set /subcategory:'Logon' /failure:enable",
            refs=["CIS 17.5.1 (L1)"],
        ),
        _r(
            "HC-WIN-0603", "Audit: process creation auditing (Sysmon-ready)",
            Severity.MEDIUM, "Audit Policy",
            {"kind": "command", "capture": "stdout",
             "command": ["auditpol", "/get", "/subcategory:'Process Creation'"],
             "expected_kind": "regex",
             "expected": r"Success",
             "fail_message": "Process Creation auditing is off.",
             "audit_hint": "4688 process auditing feeds EDR-style detections."},
            remediation_summary="Enable Process Creation success auditing.",
            script="auditpol /set /subcategory:'Process Creation' /success:enable",
            refs=["CIS 17.7.1 (L1)"],
        ),
        _r(
            "HC-WIN-0604", "PowerShell script block logging is on",
            Severity.HIGH, "Audit Policy",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging",
             "value": "EnableScriptBlockLogging",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "PowerShell script block logging is off.",
             "audit_hint": "Captures deobfuscated PowerShell at execution time."},
            remediation_summary="Enable PowerShell script block logging.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Name EnableScriptBlockLogging -Type DWord -Value 1",
            refs=["CIS 18.9.49 (L1)"],
        ),
    ]

    # --------------------------------------------------------- SMB / Network
    rules += [
        _r(
            "HC-WIN-0701", "SMB: anonymous enumeration restricted",
            Severity.HIGH, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
             "value": "RestrictAnonymousSAM",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "Anonymous SAM enumeration is allowed.",
             "audit_hint": "RestrictAnonymousSAM=1 blocks unauthenticated account listing."},
            remediation_summary="Restrict anonymous SAM enumeration.",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RestrictAnonymousSAM -Type DWord -Value 1",
            refs=["CIS 2.3.10.x (L1)"],
        ),
        _r(
            "HC-WIN-0702", "SMB server: signing always required",
            Severity.HIGH, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
             "value": "RequireSecuritySignature",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "SMB signing is not mandatory.",
             "audit_hint": "Blocks SMB relay and tampering attacks."},
            remediation_summary="Require SMB signing.",
            script="Set-SmbServerConfiguration -RequireSecuritySignature $true -Force",
            refs=["CIS 2.3.9.x (L1)"],
        ),
        _r(
            "HC-WIN-0703", "SMBv1 is disabled",
            Severity.CRITICAL, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
             "value": "SMB1",
             "expected_kind": "exact", "expected": 0,
             "allow_missing": True,
             "fail_message": "SMBv1 is enabled (EternalBlue-class risk).",
             "audit_hint": "SMB1=0 (or absent on fully patched hosts) is compliant."},
            remediation_summary="Disable SMBv1.",
            script="Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart",
            refs=["CIS 18.9.x (L1)"],
        ),
        _r(
            "HC-WIN-0704", "LLMNR is disabled",
            Severity.MEDIUM, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
             "value": "EnableMulticast",
             "expected_kind": "exact", "expected": 0,
             "fail_message": "LLMNR is enabled (responder poisoning risk).",
             "audit_hint": "EnableMulticast=0 disables LLMNR name resolution."},
            remediation_summary="Disable LLMNR.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient' -Name EnableMulticast -Type DWord -Value 0",
            refs=["CIS 18.9.31 (L1)"],
        ),
        _r(
            "HC-WIN-0705", "WPAD: no auto proxy discovery via DNS",
            Severity.LOW, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings",
             "value": "AutoDetect",
             "expected_kind": "exact", "expected": 0,
             "allow_missing": True,
             "fail_message": "WPAD auto-detection may be enabled.",
             "audit_hint": "AutoDetect=0 prevents WPAD poisoning."},
            remediation_summary="Disable WPAD auto-detect.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' -Name AutoDetect -Type DWord -Value 0",
            refs=["CIS 18.9.x (L1)"],
        ),
    ]

    # ------------------------------------------------- Screensaver / session
    rules += [
        _r(
            "HC-WIN-0801", "Interactive logon: machine inactivity limit 900s or less",
            Severity.MEDIUM, "Session Lock",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "value": "InactivityTimeoutSecs",
             "expected_kind": "max", "expected": 900,
             "allow_missing": True,
             "fail_message": "Machine inactivity limit exceeds 900 seconds.",
             "audit_hint": "InactivityTimeoutSecs locks the whole machine, not just the session."},
            remediation_summary="Set machine inactivity limit to 900 seconds or less.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name InactivityTimeoutSecs -Type DWord -Value 900",
            refs=["CIS 2.3.7.x (L1)"],
        ),
        _r(
            "HC-WIN-0802", "Screen saver password protected",
            Severity.LOW, "Session Lock",
            {"kind": "registry",
             "hive": "HKCU", "path": r"Control Panel\Desktop",
             "value": "ScreenSaverIsSecure",
             "expected_kind": "exact", "expected": "1",
             "fail_message": "Screen saver is not password protected.",
             "audit_hint": "Per-user HKCU setting; check current user's hive."},
            remediation_summary="Enable password-protected screen saver.",
            script="Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name ScreenSaverIsSecure -Value 1",
            refs=["CIS 2.3.7.x (L1)"],
        ),
        _r(
            "HC-WIN-0803", "Screen saver timeout 900s or less",
            Severity.LOW, "Session Lock",
            {"kind": "registry",
             "hive": "HKCU", "path": r"Control Panel\Desktop",
             "value": "ScreenSaveTimeOut",
             "expected_kind": "max", "expected": 900,
             "allow_missing": True,
             "fail_message": "Screen saver timeout exceeds 900 seconds.",
             "audit_hint": "HKCU per-user; combine with InactivityTimeoutSecs."},
            remediation_summary="Set screen saver timeout to 900 seconds or less.",
            script="Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name ScreenSaveTimeOut -Value 900",
            refs=["CIS 2.3.7.x (L1)"],
        ),
    ]

    # ------------------------------------------------------------ Misc (L2)
    rules += [
        _r(
            "HC-WIN-0901", "Windows Update: no automatic restart while users logged on",
            Severity.LOW, "Updates",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU",
             "value": "NoAutoRebootWithLoggedOnUsers",
             "expected_kind": "exact", "expected": 1,
             "allow_missing": True,
             "fail_message": "Windows Update may force restarts under active sessions.",
             "audit_hint": "NoAutoRebootWithLoggedOnUsers=1 protects work in progress."},
            remediation_summary="Prevent auto-restart with logged-on users.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoRebootWithLoggedOnUsers -Type DWord -Value 1",
            profile=Profile.L2,
            refs=["CIS 18.9.x (L2)"],
        ),
        _r(
            "HC-WIN-0902", "CD/DVD drive access restricted to interactive users",
            Severity.LOW, "Device Access",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon",
             "value": "AllocateCDRoms",
             "expected_kind": "exact", "expected": "1",
             "allow_missing": True,
             "fail_message": "CD/DVD access is not restricted to interactive logon.",
             "audit_hint": "AllocateCDRoms=1 limits remote access to optical media."},
            remediation_summary="Restrict CD/DVD allocation to interactive users.",
            script="Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon' -Name AllocateCDRoms -Value 1",
            profile=Profile.L2,
            refs=["CIS 17.x (L2)"],
        ),
        _r(
            "HC-WIN-0903", "Anonymous enumeration of shares restricted",
            Severity.MEDIUM, "Network",
            {"kind": "registry",
             "hive": "HKLM", "path": r"SYSTEM\CurrentControlSet\Control\Lsa",
             "value": "RestrictAnonymous",
             "expected_kind": "exact", "expected": 1,
             "fail_message": "Anonymous enumeration of shares is allowed.",
             "audit_hint": "RestrictAnonymous=1 hides share listings from null sessions."},
            remediation_summary="Restrict anonymous share enumeration.",
            script="Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RestrictAnonymous -Type DWord -Value 1",
            refs=["CIS 2.3.10.x (L1)"],
        ),
        _r(
            "HC-WIN-0904", "Guest account is disabled",
            Severity.HIGH, "Account Policies",
            {"kind": "powershell",
             "script": "(Get-LocalUser -Name Guest).Enabled",
             "as_bool": True,
             "expected_kind": "equals_bool", "expected": False,
             "fail_message": "The built-in Guest account is enabled.",
             "audit_hint": "Get-LocalUser Guest .Enabled should be False."},
            remediation_summary="Disable the built-in Guest account.",
            script="Disable-LocalUser -Name Guest",
            refs=["CIS 1.1.x (L1)"],
        ),
        _r(
            "HC-WIN-0905", "Local admin count is 2 or fewer",
            Severity.MEDIUM, "Account Policies",
            {"kind": "powershell",
             "script": "(Get-LocalGroupMember -Group Administrators | Measure-Object).Count",
             "as_int": True,
             "expected_kind": "max", "expected": 2,
             "fail_message": "More than 2 members in local Administrators.",
             "audit_hint": "Fewer local admins reduce lateral-movement risk."},
            remediation_summary="Reduce local Administrators membership.",
            steps=["Run 'lusrmgr.msc' > Groups > Administrators.",
                   "Remove unnecessary members."],
            requires_admin=True,
            refs=["CIS 1.x (L1)"],
        ),
        _r(
            "HC-WIN-0906", "Manual: review installed third-party AV",
            Severity.INFO, "Documentation",
            {"kind": "command", "capture": "stdout",
             "command": ["cmd", "/c", "echo manual-review"],
             "expected_kind": "in", "expected": "manual-review",
             "fail_message": "Manual review required.",
             "audit_hint": "Record third-party AV status in the compliance register."},
            manual=True,
            refs=["CIS guidance"],
        ),
    ]

    return rules
