export const PORTFOLIO = {
  meta: {
    title: "Offensive & Defensive Security Portfolio",
    author: "Independent Security Researcher",
    tagline: "50 hands-on projects spanning offensive security, detection engineering, digital forensics, incident response and network tooling.",
    generated: "2026",
  },

  categories: [
    { id: "network", name: "Network", color: "#00e5ff" },
    { id: "detection-monitoring", name: "Detection & Monitoring", color: "#00ff9d" },
    { id: "offensive", name: "Offensive Security", color: "#ff3b5c" },
    { id: "forensics", name: "Digital Forensics", color: "#ffa000" },
    { id: "incident-response", name: "Incident Response", color: "#ff6ac1" },
    { id: "defensive", name: "Defensive Security", color: "#4dabf7" },
    { id: "tooling", name: "Tooling & Automation", color: "#b197fc" },
    { id: "adversary", name: "Adversary Simulation", color: "#ff7847" },
    { id: "reporting", name: "Data & Reporting", color: "#d8dee9" },
  ],

  skills: [
    {
      id: "active-directory-attack-path-visualizer",
      name: "Active Directory Attack Path Visualizer",
      dir: "Active Directory attack path visualizer (BloodHound-style, lab domain)",
      category: "offensive",
      description: "BloodHound-style web app that visualizes Active Directory attack paths in a lab domain. Parses AD relationship data and runs graph algorithms (shortest path, all paths, high-value targets, kill chains) over relationship types like MemberOf, AdminTo, CanRDP and ForceChangePassword.",
      tech: "Python, Flask, vis.js, Chart.js, HTML/CSS/JavaScript",
    },
    {
      id: "arp-scanner-live-host-discovery",
      name: "ARP Scanner & Live-Host Discovery Tool",
      dir: "ARP scanner  or live-host discovery tool",
      category: "network",
      description: "Cross-platform ARP scanner that discovers live hosts on the local L2 segment from CIDRs, ranges or single IPs, reporting IP, MAC and OUI vendor. Dual probe backends: raw Scapy ARP and a zero-dependency system ping + ARP-table backend.",
      tech: "Python, Scapy, OUI vendor database, PyInstaller, unittest",
    },
    {
      id: "automated-incident-response-playbook-runner-soar-lite-nodejs",
      name: "Automated Incident Response Playbook Runner (SOAR-lite, Node.js)",
      dir: "Automated incident response playbook runner (SOAR-lite)",
      category: "incident-response",
      description: "Zero-dependency Node.js web application that lets SOC operators define response playbooks (11 step types with branches and error policies), ingest incidents, watch automation run step-by-step, and download professional HTML/JSON/Markdown/CSV incident reports.",
      tech: "Node.js, JavaScript, JSON, pkg/nexe",
    },
    {
      id: "automated-incident-response-playbook-runner-soar-lite-flask",
      name: "Automated Incident Response Playbook Runner (SOAR-lite, Flask)",
      dir: "Automated incident response playbook runner (SOAR-lite)",
      category: "incident-response",
      description: "Flask-based SOAR-lite that matches incoming incidents to playbooks and drives them through an execution engine with integration adapters (SIEM, threat intel, EDR, firewall, ticketing), NIST-style incident lifecycle, 0-100 risk scoring and standalone HTML incident reports persisted as atomic JSON files.",
      tech: "Python, Flask, JavaScript, JSON, threading",
    },
    {
      id: "bandwidth-monitor-traffic-visualizer",
      name: "Bandwidth Monitor & Traffic Visualizer (NetPulse)",
      dir: "Bandwidth monitor & traffic visualizer dashboard",
      category: "network",
      description: "Windows desktop dashboard showing live network traffic with per-process breakdowns and per-adapter charts, SQLite history rollups, threshold/quota alerts, system tray and floating HUD. One-click self-contained HTML report export.",
      tech: "Python, CustomTkinter, psutil, SQLite, PyInstaller, SVG",
    },
    {
      id: "browser-artifact-extractor",
      name: "Browser Artifact Extractor",
      dir: "Browser artifact extractor (history, cookies, cache parser)",
      category: "forensics",
      description: "Standalone desktop forensics tool that extracts and parses browser history, cookies and cache from installed browsers (Chrome, Firefox, Edge, Brave). Decrypts encrypted cookie values via Windows DPAPI and exports findings as HTML/JSON/CSV reports through a local Flask UI.",
      tech: "Python, Flask, SQLite, Jinja2, DPAPI (ctypes), PyInstaller",
    },
    {
      id: "c2-detection-lab",
      name: "C2 Detection Lab (Zeek/Suricata Signatures)",
      dir: "C2 detection lab build the C2, then build the ZeekSuricata signatures that catch it",
      category: "detection-monitoring",
      description: "Loopback-only desktop lab where you build a lightweight HTTP C2 listener and beacon client (profiled after Cobalt Strike, Sliver, Metasploit, SocGholish), then auto-generate Zeek signatures and Suricata rules that catch that exact beacon, validate them over a live session and export HTML reports.",
      tech: "Python, Tkinter, Zeek, Suricata, PyInstaller",
    },
    {
      id: "c2-traffic-obfuscation-demo",
      name: "C2 Traffic Obfuscation Techniques Demo",
      dir: "C2 traffic obfuscation techniques demo (domain fronting concepts, detection-focused)",
      category: "adversary",
      description: "Offline, detection-focused training app that simulates C2 traffic obfuscation - Base64, XOR stream, RC4 and AES-128-CBC encoding stages with entropy metrics, jittered beacon check-in schedules with regularity verdicts, and interactive domain-fronting (SNI vs Host header mismatch) exercises.",
      tech: "Python, cryptography, Tkinter, HTML/SVG, PyInstaller",
    },
    {
      id: "custom-metasploit-module",
      name: "Custom Metasploit Module for Lab Vulnerable Service",
      dir: "Custom Metasploit module for a lab-only vulnerable service",
      category: "offensive",
      description: "Studio tool that builds custom Ruby Metasploit exploit/auxiliary modules for a deliberately vulnerable lab-only HTTP service (command injection, path traversal, config disclosure). Auto-detects which vulns are live, port-scans the box, simulates the check verdict and exports polished HTML/JSON reports.",
      tech: "Python, Tkinter, Ruby (Metasploit Framework), PyInstaller",
    },
    {
      id: "custom-proxy-server-http-socks5",
      name: "Custom Proxy Server (HTTP/SOCKS5)",
      dir: "Custom proxy server (HTTPSOCKS5)",
      category: "tooling",
      description: "Local Windows forward proxy supporting HTTP/1.1, HTTPS CONNECT tunneling and SOCKS5 (RFC 1928), with optional client auth, upstream proxy chaining, a live traffic dashboard with throughput charts and rotating request logs. Ships as a single portable exe.",
      tech: "Python, asyncio, CustomTkinter, HTTP/1.1 CONNECT, SOCKS5, PyInstaller",
    },
    {
      id: "custom-subnet-calculator-vlsm",
      name: "Custom Subnet Calculator & VLSM Planner",
      dir: "Custom subnet calculator & VLSM planner",
      category: "network",
      description: "Local desktop app for IP subnetting: a custom subnet calculator deriving network/broadcast/usable ranges, masks and binary views (with reverse modes by subnet or host count), plus a VLSM planner allocating segments largest-demands-first with utilization metrics. Exports print-friendly HTML reports.",
      tech: "Python, Tkinter/ttk, unittest, PyInstaller",
    },
    {
      id: "custom-vulnerability-scanner",
      name: "Custom Vulnerability Scanner (Banner Grab + CVE Matching)",
      dir: "Custom vulnerability scanner (banner grabbing + CVE matching)",
      category: "offensive",
      description: "CLI/REPL vulnerability scanner that performs concurrent async banner grabbing across common service ports, extracts service versions with regex, and matches them against an embedded CVE signature database to produce severity-scored reports for offline reconnaissance.",
      tech: "Python, asyncio, Pydantic, regex, CVE JSON database, PyInstaller",
    },
    {
      id: "custom-wazuh-ossec-detection-rule-pack",
      name: "Custom Wazuh/OSSEC Detection Rule Pack",
      dir: "Custom WazuhOSSEC detection rule pack for a specific attack chain",
      category: "detection-monitoring",
      description: "Desktop studio for building, validating and exporting a custom Wazuh/OSSEC detection rule pack covering a rehearsed 11-stage attack chain (web initial access through exfiltration). Ships 26 embedded MITRE ATT&CK-mapped rules, an interactive attack-chain view, live XML preview and consolidated local_rules.xml export.",
      tech: "Python, Tkinter, Wazuh/OSSEC XML rules, MITRE ATT&CK, PyInstaller",
    },
    {
      id: "deleted-file-recovery-tool",
      name: "Deleted File Recovery Tool (FAT/NTFS Carving)",
      dir: "Deleted file recovery tool (FATNTFS carving)",
      category: "forensics",
      description: "Windows desktop recovery tool that finds deleted files on FAT12/16/32 and NTFS volumes using filesystem metadata analysis (deleted-marked FAT entries, $MFT record mining) plus raw magic-byte file carving, with recovery to disk and self-contained HTML reports.",
      tech: "Python, CustomTkinter, ctypes, FAT12/16/32, NTFS $MFT, file carving, PyInstaller",
    },
    {
      id: "disk-image-acquisition-hashing-toolkit",
      name: "Disk Image Acquisition & Hashing Toolkit",
      dir: "Disk image acquisition & hashing toolkit (chain-of-custody automation)",
      category: "forensics",
      description: "Local-first Windows app for forensic examiners that acquires dd-style disk images (or folder archives), streams MD5/SHA-1/SHA-256 hashing during acquisition, and automates chain of custody with an HMAC-chained, append-only, tamper-evident log plus HTML evidence reports.",
      tech: "Python, CustomTkinter, hashlib, HMAC, JSON, PyInstaller",
    },
    {
      id: "encrypted-c2-channel-demo",
      name: "Encrypted C2 Channel Demo (TLS + Blue Team Decryption)",
      dir: "Encrypted C2 channel demo (TLS-wrapped beacon) + traffic decryption for blue team study",
      category: "adversary",
      description: "Offline training sandbox that simulates a command-and-control beacon hiding inside a TLS 1.3 tunnel with custom AES-CTR + HMAC-SHA256 framing and jittered check-ins, then hands blue-teamers a decryption lab to decrypt frames one-by-one and export analyst reports, captures and recovered plaintext evidence.",
      tech: "Python, TLS 1.3, cryptography, AES-CTR, HMAC-SHA256, Tkinter",
    },
    {
      id: "endpoint-hardening-compliance-checker",
      name: "Endpoint Hardening & Compliance Checker",
      dir: "Endpoint hardening & compliance checker (CIS benchmark automation)",
      category: "defensive",
      description: "Read-only CIS-style benchmark auditor covering 45+ Windows rules across 11 categories (plus Linux/macOS contexts) with a scoring model, full PySide6 GUI and headless CLI, producing professional HTML and PDF compliance reports.",
      tech: "Python, PySide6, winreg, ReportLab, Jinja2, pytest, PyInstaller",
    },
    {
      id: "exploit-development-buffer-overflow-walkthrough",
      name: "Exploit Development Walkthrough (Buffer Overflow)",
      dir: "Exploit development walkthrough buffer overflow in a deliberately vulnerable lab binary",
      category: "offensive",
      description: "Interactive, offline 11-phase lab manual teaching classic 32-bit stack buffer overflow exploitation from recon to shell against a deliberately vulnerable binary. Features checkpoint quizzes, a simulated terminal, a live payload builder, progress persistence and HTML/PDF report export. Ships as both a web app and an Electron desktop exe.",
      tech: "JavaScript, Electron, HTML/CSS, Python, GCC/GDB/pwntools",
    },
    {
      id: "firewall-rule-auditor",
      name: "Firewall Rule Auditor & Misconfiguration Checker",
      dir: "Firewall rule auditor & misconfiguration checker",
      category: "defensive",
      description: "Web app that parses firewall rule-sets (iptables, Cisco ASA, FortiGate, pfSense, Windows netsh, Palo Alto) and detects shadowed rules, ALLOW-overrides-DENY, world-open ANY/ANY, duplicates and port/protocol mismatches, producing a graded 0-100 security posture with reports. Runs as Flask app or standalone exe.",
      tech: "Python, Flask, JavaScript, Chart.js, HTML/CSS, PyInstaller",
    },
    {
      id: "forensic-report-generator",
      name: "Forensic Report Generator",
      dir: "Forensic report generator (findings, evidence log, exhibit index)",
      category: "forensics",
      description: "Single-file desktop application for building professional forensic investigation reports: case information, findings with severity/status, an evidence log with chain-of-custody records, and an exhibit index, all exported as an industry-standard HTML report with a warm neutral palette.",
      tech: "Python, Tkinter, JSON, HTML, PyInstaller",
    },
    {
      id: "honeypot-ssh-http-attacker-fingerprinting",
      name: "Honeypot (SSH-HTTP) with Attacker Fingerprinting",
      dir: "Honeypot (SSH-HTTP) with attacker fingerprinting",
      category: "detection-monitoring",
      description: "Self-contained honeypot exposing fake SSH (paramiko) and HTTP (raw socket) services that logs every auth attempt, command and request header, then builds a behavioral fingerprint per attacker with tool detection and risk scoring, surfaced via a Flask dashboard with HTML report export.",
      tech: "Python, Flask, paramiko, SQLite, JavaScript, HTML",
    },
    {
      id: "host-based-intrusion-detection-agent",
      name: "Host-Based Intrusion Detection Agent (FIM + Process Monitor)",
      dir: "Host-based intrusion detection agent (file integrity + process monitor)",
      category: "detection-monitoring",
      description: "Windows HIDS agent combining File Integrity Monitoring (baseline hashing and drift detection) with process monitoring against an auto-learned whitelist and resource thresholds. Emits severity-ranked alerts, ships a Tkinter dashboard and exports HTML/JSON/TXT/CSV reports.",
      tech: "Python, Tkinter, psutil, SQLite, hashlib, PyInstaller",
    },
    {
      id: "lightweight-siem-log-correlator",
      name: "Lightweight SIEM Log Correlator (Ingest-Normalize-Alert)",
      dir: "Lightweight SIEM log correlator (ingest \u2192 normalize \u2192 alert)",
      category: "detection-monitoring",
      description: "Lightweight, self-contained SIEM web app implementing the full Ingest-Normalize-Correlate-Alert-Report pipeline with rule-based temporal correlation, sliding time windows, risk scoring and escalation tiers. No ELK stack and no external database - state is JSON-snapshotted in memory.",
      tech: "Python, Flask, JavaScript, regex, JSON, HTML/CSS",
    },
    {
      id: "load-balancer-simulator",
      name: "Load Balancer Simulator with Health Checks",
      dir: "Load balancer simulator with health checks",
      category: "network",
      description: "Desktop application that visually simulates a reverse-proxy load balancer distributing traffic across backends using 8 algorithms, with active/passive health checks, a circuit-breaker state machine, traffic-pattern generators, chaos-engineering controls and live topology visualization.",
      tech: "Python, PyQt6, pyqtgraph, aiohttp, pydantic, numpy, qasync, PyInstaller",
    },
    {
      id: "log-anonymizer-redactor",
      name: "Log Anonymizer & Redactor",
      dir: "Log anonymizerredactor for safe log sharing",
      category: "tooling",
      description: "Desktop utility that desensitizes raw logs before sharing by deterministically masking, hashing or tokenizing 15 categories of sensitive data (IPv4/IPv6, emails, card numbers, JWTs, API keys, AWS ARNs, MACs). Preserves log structure and produces an HTML audit report, fully offline.",
      tech: "Python, CustomTkinter, regex, HTML, PyInstaller, pytest",
    },
    {
      id: "memory-forensics-analyzer",
      name: "Memory Forensics Analyzer (Volatility Workflow)",
      dir: "Memory forensics analyzer (Volatility pluginworkflow)",
      category: "forensics",
      description: "Desktop-first application that guides an analyst through a structured Volatility plugin workflow for Windows memory images: acquisition and verification, profile identification, process/network/malware triage, kernel and registry analysis, extraction and reporting - bundled as an offline GUI with HTML report output.",
      tech: "Python, PySide6, Volatility3, PyInstaller",
    },
    {
      id: "minimal-c2-beacon-detection-lab",
      name: "Minimal C2 Architecture Beacon + Listener (Educational Skeleton)",
      dir: "Minimal C2 architecture beacon + listener over HTTP (educational skeleton)",
      category: "detection-monitoring",
      description: "Defensive, educational beacon-detection lab (the analysis side of HTTP C2): it feeds web-server access logs or PCAPs through a standard-library analyzer that groups traffic by source/destination and scores interval regularity, jitter and Gini impurity to flag machine-regular beaconing. Local web dashboard and HTML report download; no implant functionality by design.",
      tech: "Python, stdlib only, PCAP parsing, HTTP server, PyInstaller",
    },
    {
      id: "mobile-device-forensics-workflow",
      name: "Mobile Device Forensics Workflow (Android Logical Extraction)",
      dir: "Mobile device forensics workflow (Android backuplogical extraction, lab device)",
      category: "forensics",
      description: "Lab toolkit that walks an examiner through Android logical-acquisition: case intake, ADB-based backup/extraction (contacts, SMS, apps, screenshots), artifact parsing, SHA-256 evidence hashing with a chain-of-custody CSV, per-case audit trails and self-contained HTML report download.",
      tech: "Python, PySide6, ADB, SQLite, zlib/tar, hashlib, PyInstaller",
    },
    {
      id: "packet-sniffer-raw-sockets",
      name: "Packet Sniffer from Raw Sockets",
      dir: "Packet sniffer from raw sockets",
      category: "network",
      description: "Colorful tabbed desktop packet sniffer that captures live traffic using raw sockets (SIO_RCVALL on Windows, AF_PACKET on Linux) with no third-party packet libraries. Decodes IPv4/TCP/UDP/ICMP, supports Wireshark-style display filters, live stats and self-contained HTML report export.",
      tech: "Python, Tkinter, raw sockets (SIO_RCVALL / AF_PACKET), PyInstaller",
    },
    {
      id: "password-strength-auditor-cracker",
      name: "Password Strength Auditor & Wordlist-Based Cracker",
      dir: "Password strength auditor & wordlist-based cracker (own hashes only)",
      category: "offensive",
      description: "VaultGuard is a Windows desktop app that audits password strength with entropy, pattern and search-space scoring, and performs threaded wordlist-based cracking with mangling rules against user-owned MD5/SHA-family hashes. Produces self-contained HTML reports.",
      tech: "Python, CustomTkinter, hashlib, threading, HTML, PyInstaller",
    },
    {
      id: "phishing-email-analyzer",
      name: "Phishing Email Analyzer (Header/URL/Attachment Triage)",
      dir: "Phishing email analyzer (headerURLattachment triage tool)",
      category: "incident-response",
      description: "Desktop triage tool that analyzes suspicious emails across three vectors: RFC-5322 headers (SPF/DKIM/DMARC, spoofing signals), embedded URLs (de-obfuscation, dangerous patterns) and attachments (hash + risk extensions). Produces a weighted risk score with exportable HTML forensic reports.",
      tech: "Python, CustomTkinter, email (RFC 5322), urllib, hashlib, PyInstaller",
    },
    {
      id: "port-scanner",
      name: "Port Scanner (TCP Connect, SYN, Service-Version Detection)",
      dir: "Port scanner (TCP connect, SYN, and service-version detection)",
      category: "offensive",
      description: "Colorful terminal port scanner supporting TCP connect scans, SYN half-open scans via Scapy, and service/version detection with typed probes. Features thread-pool concurrency, randomized port order, per-host memory hints and JSON session persistence.",
      tech: "Python, Scapy, socket, colorama, PyInstaller",
    },
    {
      id: "purple-team-capstone",
      name: "Purple Team Capstone (Red Builds, Blue Detects, MITRE ATT&CK)",
      dir: "Purple team capstone red builds, blue detects, both document MITRE ATT&CK mapping",
      category: "adversary",
      description: "Self-contained purple-team lab app where the red team simulates 9 MITRE ATT&CK techniques inside a sandboxed lab target directory while the blue team hunts them with 9 sigma-style detection rules. Includes a technique x rule coverage matrix, exercise timeline and scoring, and HTML report export.",
      tech: "Python, Tkinter, MITRE ATT&CK, PyInstaller",
    },
    {
      id: "ransomware-behavior-analysis",
      name: "Ransomware Behavior Analysis Report",
      dir: "Ransomware behavior analysis report (encryption pattern study, sample from public repo)",
      category: "reporting",
      description: "Web-based analysis platform studying ransomware behavior, encryption patterns (hybrid AES-RSA, sparse-file encryption, multi-threading) and attack methodologies from public IOC repositories. Features an ATT&CK dashboard, 9-stage kill-chain timeline, sample repository and downloadable HTML analysis reports.",
      tech: "JavaScript, Electron, HTML/CSS, Chart.js, JSON",
    },
    {
      id: "real-time-soc-dashboard-3d-topology",
      name: "Real-Time SOC Dashboard with 3D Network Topology",
      dir: "Real-time SOC dashboard with 3D network topology visualization",
      category: "detection-monitoring",
      description: "Electron desktop app rendering a live Security Operations dashboard with a Three.js WebGL 3D network topology visualization, animated traffic along links, real-time KPI metrics, a streaming threat feed and alerting panels. Runs fully offline with a secure sandboxed renderer.",
      tech: "Electron, Node.js, Three.js (WebGL), HTML/CSS/JavaScript",
    },
    {
      id: "red-team-engagement-report-generator",
      name: "Red Team Engagement Report Generator",
      dir: "Red team engagement report generator (findings \u2192 CVSS \u2192 executive summary)",
      category: "reporting",
      description: "Self-contained Windows desktop app that converts red team engagement findings into CVSS v3.1 scores via a visual metric calculator, auto-generates a severity-aware executive summary, and outputs polished self-contained HTML engagement reports with a JSON datastore.",
      tech: "Python, Tkinter, CVSS v3.1, JSON, PyInstaller",
    },
    {
      id: "reverse-engineering-ctf-toolkit",
      name: "Reverse-Engineering CTF Challenge Solver Toolkit",
      dir: "Reverse-engineering CTF challenge solver toolkit",
      category: "offensive",
      description: "Windows desktop toolkit for triaging and solving reverse-engineering and crypto CTF challenges: file identification, strings, hex dump, entropy analysis, encoding toolbox, XOR/Caesar/Atbash/Vigenere solvers and one-click self-contained HTML reports.",
      tech: "Python, Tkinter, HTML, PyInstaller",
    },
    {
      id: "soc-alert-triage-dashboard",
      name: "SOC Alert Triage Dashboard (Severity Scoring + Dedup)",
      dir: "SOC alert triage dashboard (severity scoring + dedup)",
      category: "incident-response",
      description: "Client-side browser application for SOC alert triage that runs entirely without a backend. It auto-scores alerts on a 1-10 scale, deduplicates using source/destination/type hashing plus fuzzy matching and time-window grouping, and exports self-contained HTML reports with SVG charts.",
      tech: "JavaScript, HTML/CSS, SVG charts, localStorage",
    },
    {
      id: "social-engineering-awareness-simulator",
      name: "Social Engineering Awareness Simulator (SeaSim)",
      dir: "Social engineering awareness simulator (internal phishing test platform)",
      category: "adversary",
      description: "Windows desktop platform (SeaSim) for running authorized, simulated internal phishing awareness campaigns. Enforces non-negotiable safety constraints in code - no credential harvesting fields, loopback-only SMTP stub, mandatory 3-step consent workflow, rate caps - and tracks susceptibility with just-in-time training windows.",
      tech: "Python, Tkinter, JSON, threading, SMTP, queue",
    },
    {
      id: "sql-injection-detection-tool",
      name: "SQL Injection Detection Tool (Defensive)",
      dir: "SQL injection detection tool (defensive-oriented, flags vulnerable params)",
      category: "defensive",
      description: "Defensive-oriented SQLi detector (SQLInspect) that flags vulnerable parameters via offline weighted scoring of canonical payload signatures, syntax patterns, SQL keyword density and DBMS error signatures. Includes optional consent-gated live probing and PDF/CSV/JSON/HTML report export.",
      tech: "Python, Flask, regex, urllib, ReportLab, JavaScript, HTML/CSS",
    },
    {
      id: "threat-actor-ttp-profiler",
      name: "Threat Actor TTP Profiler (MITRE ATT&CK Mapping)",
      dir: "Threat actor TTP profiler from analyzed sample set (MITRE ATT&CK mapping)",
      category: "defensive",
      description: "Desktop tool that analyzes a set of suspicious samples (PE binaries and scripts) through imports, embedded strings, entropy and optional YARA, maps detected techniques to 70+ MITRE ATT&CK rules with confidence scoring, and ranks findings against 14 built-in threat-actor profiles before exporting an ATT&CK Navigator-style HTML report.",
      tech: "Python, CustomTkinter, YARA, pefile, MITRE ATT&CK, JSON, PyInstaller",
    },
    {
      id: "threat-intel-feed-aggregator",
      name: "Threat-Intel Feed Aggregator (IOC + Auto-Blocklist)",
      dir: "Threat-intel feed aggregator (IOC ingestion + auto-blocklist)",
      category: "defensive",
      description: "Self-hosted web pipeline that ingests open-source IOC feeds (TXT/CSV/JSON), extracts and normalizes IPs, domains, URLs and hashes, scores confidence/severity into SQLite, and generates firewall/DNS blocklist artifacts (pfSense, iptables, hosts, BIND) plus downloadable reports.",
      tech: "Python, Flask, SQLite, requests, regex, JavaScript",
    },
    {
      id: "timeline-builder",
      name: "Timeline Builder from Filesystem & Log Artifacts",
      dir: "Timeline builder from filesystem + log artifacts",
      category: "forensics",
      description: "Windows desktop tool that reconstructs a chronological event timeline from a folder's filesystem metadata (created/modified/accessed) and timestamped log artifacts, normalizing many date formats onto one axis. Exports searchable, sortable self-contained HTML reports.",
      tech: "Python, CustomTkinter, regex, HTML/JavaScript, PyInstaller",
    },
    {
      id: "vpn-tunnel-builder-wireguard",
      name: "VPN Tunnel Builder (WireGuard Automation)",
      dir: "VPN tunnel builder (WireGuard automation script)",
      category: "network",
      description: "Desktop GUI (wgbuilder) that automates WireGuard tunnel setup: generates wg-compatible X25519 keypairs (pure-Python RFC 7748 implementation, test-vector verified), assembles server and per-peer client .conf files, produces QR codes for mobile import, and exports all artifacts plus self-contained HTML reports.",
      tech: "Python, Tkinter/ttk, X25519 (RFC 7748), qrcode, Pillow, PyInstaller",
    },
    {
      id: "web-app-fuzzer",
      name: "Web App Fuzzer for Input Validation Testing",
      dir: "Web app fuzzer for input validation testing",
      category: "offensive",
      description: "Flask-based web fuzzer that fires 12 classes of security payloads (SQLi, XSS, command injection, path traversal, SSTI, SSRF, XXE, open redirect, JWT/auth) through target fields with configurable threading. A weighted risk model detects reflection, error leakage, timing and semantic anomalies, exported as HTML reports.",
      tech: "Python, Flask, JavaScript, threading, HTML/CSS, regex",
    },
    {
      id: "windows-event-log-correlation",
      name: "Windows Event Log Correlation for Intrusion Timeline",
      dir: "Windows Event Log correlation tool for intrusion timeline",
      category: "detection-monitoring",
      description: "Windows desktop tool that collects Security/System/.evtx logs via wevtutil, correlates events against MITRE ATT&CK detection rules (excess/sequence/single evaluators), assigns kill-chain phases, groups multi-stage incident chains, and exports a self-contained HTML intrusion timeline report.",
      tech: "Python, Tkinter, wevtutil, ElementTree, MITRE ATT&CK, PyInstaller",
    },
    {
      id: "wireless-network-auditor",
      name: "Wireless Network Auditor (WPA Handshake Capture)",
      dir: "Wireless network auditor (WPA handshake capture in your own lab AP)",
      category: "network",
      description: "Self-contained web application that scans the 2.4/5 GHz spectrum, targets a lab access point, captures WPA/WPA2 4-way EAPOL handshakes (optionally accelerating with deauth frames via airodump/aireplay-ng in live mode), records sessions in SQLite and generates downloadable HTML audit reports.",
      tech: "Python, Flask, SQLite, airodump-ng / aireplay-ng, JavaScript",
    },
    {
      id: "xss-payload-tester",
      name: "XSS Payload Tester for Lab Web Apps",
      dir: "XSS payload tester for your own lab web app",
      category: "offensive",
      description: "Local web tool that fires 29 built-in XSS payloads across 6 categories (basic, tag/event, JS context, encoding, polyglot, scanner) at your own lab web app via GET, POST form or POST JSON. Detects reflection and dangerous contexts with marker-based verdicts and exports self-contained HTML scan reports.",
      tech: "Python, Flask, JavaScript, HTML/CSS, requests, PyInstaller",
    },
    {
      id: "yara-rule-generator",
      name: "YARA Rule Generator from Malware Sample Sets",
      dir: "YARA rule generator from malware sample sets",
      category: "tooling",
      description: "YaraForge desktop app that analyzes a set of malware samples, extracts discriminative static features (strings, PE imports, entropy, imphash), scores them across the set, and auto-generates a consolidated YARA rule with condition logic and an HTML report with one-click .yar download.",
      tech: "Python, Tkinter, YARA, pefile, hashlib, PyInstaller",
    },
    {
      id: "yara-malware-family-classifier",
      name: "YARA-Based Malware Family Classifier",
      dir: "YARA-based malware family classifier",
      category: "defensive",
      description: "Desktop GUI that classifies local files into malware families using the yara-python engine with a thread-pooled, read-only scanner, per-rule enable/disable and config persistence. Results are aggregated per family with severity/confidence and exported as self-contained HTML (SVG donut), CSV and JSON reports.",
      tech: "Python, Tkinter, YARA (yara-python), ThreadPoolExecutor, HTML/SVG",
    },
  ],
};

export function categoryById(id) {
  return PORTFOLIO.categories.find((c) => c.id === id) || null;
}

export function skillById(id) {
  return PORTFOLIO.skills.find((s) => s.id === id) || null;
}

export function skillsByCategory(id) {
  return PORTFOLIO.skills.filter((s) => s.category === id);
}

export function rightCol(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.6 ? "#0a0f1e" : "#eaf4ff";
}