# =============================================================================
#  YARA rule generation
# =============================================================================
import hashlib
import itertools
import re
import uuid
from datetime import date

from .lexicon import DETECTION_CONCEPTS, KNOWN_PROCESSES

# Map concepts -> YARA string hints (values that often appear in malware)
CONCEPT_YARA_STRINGS = {
    "powershell_execution": ["powershell", "-windowstyle", "invoke-expression",
                             "downloadstring", "iex(", "new-object net.webclient"],
    "cmd_execution": ["cmd.exe", "/c ", "-command"],
    "obfuscation": ["frombase64string", "encodedcommand", "iex", "xor",
                    ".base64", "char(", "[]::frombase64"],
    "credential_dumping": ["sekurlsa", "logonpasswords", "privilege::debug",
                           "lsass.exe", "minidump", "sekurlsa::"],
    "network_connection": ["tcpclient", "net.webclient", "downloadstring",
                           "invoke-webrequest", "socket", "connect("],
    "download": ["invoke-webrequest", "downloadfile", "downloadstring", "curl",
                 "wget", "bitsadmin", "webclient.download"],
    "upload_exfiltration": ["uploadfile", "uploadstring", "invoke-restmethod",
                            "webclient.upload", "putfile"],
    "file_creation": ["out-file", "set-content", "streamwriter", "create(",
                      "file.writeallbytes", "copy-item"],
    "registry_modification": ["set-itemproperty", "reg add", "run", "runonce",
                              "hkey_current_user", "hkey_local_machine"],
    "startup_persistence": ["startup", "startup folder", "all users", "appdata"],
    "scheduled_task": ["schtasks", "/create", "/sc", "onlogon", "onstart"],
    "recon_discovery": ["whoami", "hostname", "net user", "net group",
                        "ipconfig", "systeminfo", "tasklist", "get-aduser",
                        "domain admins"],
    "lateral_movement": ["psexec", "winrm", "wmic", "net use", "mstsc",
                         "createprocess", "logon"],
    "defense_disabling": ["set-mppreference", "disable", "reagentc",
                          "wevtutil", "sc stop", "netsh advfirewall"],
    "injection": ["virtualalloc", "writeprocessmemory", "createremotethread",
                  "queueuserapc", "ntmapviewofsection", "resumehandle"],
    "data_destruction": ["rm -rf", "del /s", "format", "cipher /w", "wevtutil cl"],
    "c2_beaconing": ["beacon", "callback", "c2", "http://", "https://", "sleep"],
    "phishing": ["macro", "automacro", "vbastring", "document.open", "activeworkbook",
                 "enablecontent", "shell(", "payload"],
    "impact": ["ransom", "encrypt", "bitlocker", "lock-bitlocker", "vssadmin"],
    "keylog": ["getasynckeystate", "setwindowshookex", "keylogger"],
    "service_creation": ["sc create", "create service", "windows service",
                         "createservice", "startservice"],
    "scripting": ["wscript", "cscript", "mshta", "regsvr32", "+("],
}


def _meta_value(value):
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    return str(value)


def build_yara(text, entities, hits, created=None):
    """Build a YARA rule mirroring what the engine understood."""
    name = _rule_name(hits, entities)
    description = (f"Autogenerated rule for: '{re.sub(r'\\s+', ' ', text)[:110]}'"
                   .replace('\\', ''))
    mitre = sorted({t for h in hits.hits for t in h.get("mitre", [])})
    strings = _strings(text, entities, hits)
    condition = _condition(strings, text, entities)

    meta = {
        "author": _meta_value("NL2Rule Translator"),
        "description": _meta_value(description),
        "mitre_attack": _meta_value(",".join(mitre) if mitre else "T1059"),
        "date": _meta_value(created or date.today().strftime("%Y-%m-%d")),
        "hash_example": _meta_value(_hash(text)),
    }

    lines = [f"rule {name}", "{"]
    lines.append("    meta:")
    for k, v in meta.items():
        lines.append(f"        {k} = {v}")
    lines.append("")
    lines.append("    strings:")
    for i, (key, val) in enumerate(strings):
        modifier = val.get("mod") or "ascii"
        lines.append(f"        ${key} = {_meta_value(val['value'])} {modifier}")
    lines.append("")
    lines.append("    condition:")
    lines.append(f"        {condition}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _rule_name(hits, entities):
    parts = []
    for c in ("credential_dumping", "c2_beaconing", "lateral_movement", "impact",
              "powershell_execution", "obfuscation", "cmd_execution",
              "registry_modification", "download", "scheduled_task"):
        if c in hits.concept_keys():
            label = DETECTION_CONCEPTS[c]["label"].replace(" / ", "_").replace(" ", "_")
            parts.append(label)
    if not parts and entities.get("process"):
        parts.append("Process_Execution")
    if not parts:
        parts.append("Suspicious")
    detail = ""
    if entities.get("process"):
        detail = entities.get("process")[0]["value"]
    elif entities.get("domain"):
        detail = entities.get("domain")[0]["value"]
    elif entities.get("ip"):
        detail = entities.get("ip")[0]["value"]
    name = "_".join(parts + ([detail] if detail else []))
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)[:80]
    if not name:
        name = "Suspicious"
    if not re.match(r"^[A-Za-z_]", name):
        name = "R_" + name
    return name


def _strings(text, entities, hits):
    """Ordered list of (identifier, {value, mod}) candidates."""
    candidates = []
    seen = set()

    def add(value, mod="ascii", limit=None):
        if not value or len(value) > 256:
            return
        value = value.strip('"')
        if not value or value in seen:
            return
        if limit and len(candidates) >= limit:
            return
        seen.add(value)
        candidates.append((value, mod))

    # concept-driven strings
    for h in hits.hits:
        for s in CONCEPT_YARA_STRINGS.get(h["concept"], []):
            add(s, "ascii")

    # entity-driver strings: domains, ips, urls, mutexes, strings, files
    for item in itertools_chain(
        entities.get("domain"),
        entities.get("url"),
        entities.get("ip"),
        entities.get("mutex"),
        entities.get("pipe"),
        entities.get("file_path"),
        entities.get("string"),
    ):
        add(item["value"], "ascii" if item["value"].isascii() else "wide")

    # filters
    filtered = []
    for v, m in candidates:
        if len(v) == 1 or v.lower() in {"the", "a", "an", "and", "this", "that", "of"}:
            continue
        if not re.search(r"[a-zA-Z0-9]", v):
            continue
        filtered.append((v, m))

    named = []
    used = set()
    for i, (v, m) in enumerate(filtered[:18], start=1):
        ident = f"s{i}"
        while ident in used:
            ident += "_"
        used.add(ident)
        named.append((ident, {"value": v, "mod": m}))
    return named


def itertools_chain(*lists):
    out = []
    for lst in lists:
        out.extend(lst or [])
    return out


def _condition(strings, text, entities):
    if not strings:
        return "any of them"
    # Common denominator: any of the strings plus a file-neutral preamble.
    return "any of them"


def _hash(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16].upper()