"""Subnet math + WireGuard config (.conf) builders.

Output format mirrors what ``wg-quick`` / the official apps consume:
INI-style ``[Interface]`` / ``[Peer]`` sections.
"""

import ipaddress
import re

DEFAULT_SUBNET = "10.0.0.0/24"
DEFAULT_SERVER_IP_OFFSET = 0  # first usable host is the server


def normalize_subnet(cidr: str) -> ipaddress.IPv4Network:
    return ipaddress.IPv4Network(str(cidr).strip(), strict=False)


def host_at_offset(cidr: str, offset: int) -> ipaddress.IPv4Address:
    """Return the (offset+1)-th usable host on a network.

    offset 0 -> first usable host (network+1).
    """
    net = normalize_subnet(cidr)
    hosts = net.hosts()
    for _ in range(offset):
        next(hosts)
    return next(hosts)


def server_address_for(cidr: str) -> str:
    return str(host_at_offset(cidr, DEFAULT_SERVER_IP_OFFSET))


def next_peer_candidates(cidr: str, taken: list[str]):
    """Yield usable host IPs never colliding with existing ones."""
    taken = {str(ipaddress.IPv4Address(t)) for t in taken}
    for h in normalize_subnet(cidr).hosts():
        s = str(h)
        if s not in taken:
            yield s


def describe_subnet(cidr: str) -> str:
    net = normalize_subnet(cidr)
    hosts = list(net.hosts())
    first = hosts[0] if hosts else net.network_address
    last = hosts[-1] if hosts else net.broadcast_address
    return (
        f"{net.network_address}/{net.prefixlen}  range "
        f"{first} - {last}  broadcast {net.broadcast_address}"
    )


def build_server_config(server: dict, peers: list[dict]) -> str:
    """WireGuard server config: one [Peer] per client."""
    if not server.get("private_key"):
        raise ValueError("server private key not set")
    lines = ["[Interface]", f"PrivateKey = {server['private_key']}",
             f"ListenPort = {int(server['listen_port'])}",
             f"Address = {server['address']}"]
    if server.get("mtu"):
        lines.append(f"MTU = {int(server['mtu'])}")
    if server.get("post_up"):
        lines.append(f"PostUp = {server['post_up']}")
    if server.get("post_down"):
        lines.append(f"PostDown = {server['post_down']}")
    lines.append("")
    for p in sorted(peers, key=lambda x: x.get("name", "")):
        lines.append("[Peer]")
        lines.append(f"# {p['name']}")
        lines.append(f"PublicKey = {p['public_key']}")
        lines.append(f"AllowedIPs = {p['allowed_ips']}")
        if p.get("keepalive"):
            lines.append(f"PersistentKeepalive = {int(p['keepalive'])}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_client_config(server: dict, peer: dict, profile_name: str) -> str:
    """WireGuard client config that a phone/PC imports, incl. Endpoint + QR."""
    if not peer.get("private_key"):
        raise ValueError(f"peer '{peer.get('name', '?')}' has no private key")
    if not server.get("public_key"):
        raise ValueError("server public key not set")
    lines = ["[Interface]",
             f"PrivateKey = {peer['private_key']}",
             f"Address = {peer['ip']}",
             f"DNS = {server.get('dns') or '1.1.1.1'}"]
    if server.get("mtu"):
        lines.append(f"MTU = {int(server['mtu'])}")
    lines.append("")
    lines.append("[Peer]")
    lines.append(f"PublicKey = {server['public_key']}")
    ep = server.get("endpoint_host", "").strip()
    if not ep:
        raise ValueError("server endpoint host must be set (public IP/DNS)")
    lines.append(f"Endpoint = {ep}:{int(server['listen_port'])}")
    lines.append(f"AllowedIPs = {peer.get('allowed_ips') or str(peer['ip']) + '/32'}")
    if peer.get("keepalive"):
        lines.append(f"PersistentKeepalive = {int(peer['keepalive'])}")
    lines.append("")
    lines.append("# Generated by VPN Tunnel Builder - " + profile_name)
    return "\n".join(lines).rstrip() + "\n"


_SECTION = re.compile(r"^\s*\[([^\]]+)\]\s*$")
_KV = re.compile(r"^\s*#?\s*([A-Za-z0-9_.]+)\s*=\s*(.*?)\s*$")


def parse_config(text: str) -> dict:
    """Tiny .conf parser; returns {'Interface': {...}, 'Peer': [{...}, ...]}."""
    text = text.replace("\r\n", "\n")
    cur = None
    out = {"Interface": {}, "Peers": []}
    peer_index = -1
    for line in text.splitlines():
        s = _SECTION.match(line)
        if s:
            name = s.group(1).strip()
            if name.lower() == "peer":
                peer_index += 1
                out["Peers"].append({})
                cur = out["Peers"][peer_index]
            else:
                peer_index = -1
                cur = out["Interface"]
            continue
        kv = _KV.match(line)
        if kv and cur is not None:
            cur[kv.group(1)] = kv.group(2)
    return out