# =============================================================================
#  Lexicon & knowledge base for the NL -> Rule translator
#
#  Central definitions used by the concept & entity extractors:
#    - LOLBins / well-known tooling
#    - detection concepts (natural language -> Sigma logsource + fields)
#    - MITRE ATT&CK technique mapping
#    - SANS / Sigma category mapping
# =============================================================================

# ---------------------------------------------------------------------------
# Well-known process / tool names (lowercase, no .exe)
# value: (display name, mitre tag, short hint)
# ---------------------------------------------------------------------------
KNOWN_PROCESSES = {
    "powershell":           ("Windows PowerShell",      "execution",     "T1059.001"),
    "pwsh":                 ("PowerShell Core",         "execution",     "T1059.001"),
    "cmd":                  ("Windows Command Shell",   "execution",     "T1059.003"),
    "cmd.exe":              ("Windows Command Shell",   "execution",     "T1059.003"),
    "rundll32":             ("Rundll32",                "execution",     "T1218.011"),
    "wscript":              ("Windows Script Host",     "execution",     "T1218"),
    "cscript":              ("Windows Script Host",     "execution",     "T1218"),
    "mshta":                ("MSHTA",                   "execution",     "T1218.005"),
    "regsvr32":             ("Regsvr32",                "execution",     "T1218.010"),
    "regsvr32.exe":         ("Regsvr32",                "execution",     "T1218.010"),
    "certutil":             ("Certutil",                "defense_evasion", "T1140"),
    "certutil.exe":         ("Certutil",                "defense_evasion", "T1140"),
    "whoami":               ("Whoami",                  "discovery",     "T1033"),
    "net":                  ("Net",                     "discovery",     "T1016"),
    "net.exe":              ("Net",                     "discovery",     "T1016"),
    "ipconfig":             ("Ipconfig",                "discovery",     "T1016"),
    "nslookup":             ("Nslookup",                "discovery",     "T1048"),
    "systeminfo":           ("Systeminfo",              "discovery",     "T1082"),
    "tasklist":             ("Tasklist",                "discovery",     "T1057"),
    "reg":                  ("Reg",                     "discovery",     "T1012"),
    "reg.exe":              ("Reg",                     "discovery",     "T1012"),
    "schtasks":             ("Schtasks",                "persistence",   "T1053.005"),
    "schtasks.exe":         ("Schtasks",                "persistence",   "T1053.005"),
    "mimikatz":             ("Mimikatz",                "credential_access", "T1003.001"),
    "mimikatz.exe":         ("Mimikatz",                "credential_access", "T1003.001"),
    "procump":              ("ProcDump",                "credential_access", "T1003.001"),
    "procdump":             ("ProcDump",                "credential_access", "T1003.001"),
    "procdump64":           ("ProcDump64",              "credential_access", "T1003.001"),
    "dumpit":               ("DumpIt (Mimikatz)",       "credential_access", "T1003.001"),
    "secretsdump":          ("Impacket secretsdump",    "credential_access", "T1003"),
    "pwdump":               ("Pwdump",                  "credential_access", "T1003"),
    "wce":                  ("Windows Credential Editor", "credential_access", "T1003"),
    "cain.exe":             ("Cain",                    "credential_access", "T1003"),
    "ntdsutil":             ("ntdsutil",                "credential_access", "T1003.003"),
    "vssadmin":             ("Vssadmin",                "defense_evasion", "T1490"),
    "wmic":                 ("WMIC",                    "execution",     "T1047"),
    "wmic.exe":             ("WMIC",                    "execution",     "T1047"),
    "bitsadmin":            ("Bitsadmin",               "defense_evasion", "T1197"),
    "bitsadmin.exe":        ("Bitsadmin",               "defense_evasion", "T1197"),
    "curl":                 ("Curl",                    "command_and_control", "T1105"),
    "wget":                 ("Wget",                    "command_and_control", "T1105"),
    "nc":                   ("Netcat",                  "command_and_control", "T1071"),
    "ncat":                 ("Ncat",                    "command_and_control", "T1071"),
    "socat":                ("Socat",                   "command_and_control", "T1071"),
    "msfvenom":             ("MSFvenom",                "execution",     "T1221"),
    "python":               ("Python",                  "execution",     "T1059.006"),
    "python.exe":           ("Python",                  "execution",     "T1059.006"),
    "msbuild":              ("MSBuild",                 "defense_evasion", "T1127.001"),
    "csc.exe":              ("C# Compiler",             "defense_evasion", "T1127"),
    "rar":                  ("WinRAR",                  "collection",    "T1560.001"),
    "7z":                   ("7-Zip",                   "collection",    "T1560.001"),
    "7z.exe":               ("7-Zip",                   "collection",    "T1560.001"),
    "explorer":             ("Windows Explorer",        "lateral_movement", "T1021"),
    "wmiprvse":             ("WMI Provider",            "lateral_movement", "T1047"),
    "sc.exe":               ("Service Control",         "persistence",   "T1543.003"),
    "regsvc":               ("Registry Service",        "persistence",   "T1547"),
    "ssh":                  ("OpenSSH client",          "command_and_control", "T1021.004"),
    "powershell_ise":       ("PowerShell ISE",          "execution",     "T1059.001"),
    "mshta.exe":            ("MSHTA",                   "execution",     "T1218.005"),
    "regedit":              ("Registry Editor",         "discovery",     "T1012"),
    "taskmgr":              ("Task Manager",            "discovery",     "T1057"),
    "at":                   ("AT (Task Scheduler)",     "persistence",   "T1053.002"),
    "at.exe":               ("AT (Task Scheduler)",     "persistence",   "T1053.002"),
    "base64.exe":           ("Base64",                  "defense_evasion", "T1027.001"),
    "svchost":              ("Service Host",            "execution",     None),
    "svchost.exe":          ("Service Host",            "execution",     None),
    "conhost":              ("Console Host",            "execution",     None),
    "conhost.exe":          ("Console Host",            "execution",     None),
    "agent.py":             ("Python Agent",            "execution",     "T1059.006"),
    "beacon.exe":           ("Cobalt Strike Beacon",    "command_and_control", "T1071"),
    "loader.exe":           ("Loader",                  "execution",     "T1105"),
    "metasploit":           ("Metasploit",              "execution",     "T1221"),
    "nmap":                 ("Nmap",                    "discovery",     "T1046"),
    "hydra":                ("Hydra",                   "credential_access", "T1110"),
    "john":                 ("John the Ripper",         "credential_access", "T1110"),
    "hashcat":              ("Hashcat",                 "credential_access", "T1110"),
    "bloodhound":           ("BloodHound",              "discovery",     "T1087"),
    "sharp":                ("SharpHound",              "discovery",     "T1087"),
    "ps1":                  ("PowerShell Script",       "execution",     "T1059.001"),
    "bat":                  ("Batch File",              "execution",     "T1059.003"),
    "dll":                  ("DLL",                     "execution",     "T1204.002"),
    "vbs":                  ("VBScript",                "execution",     "T1059.005"),
    "js":                   ("JavaScript File",         "execution",     "T1059.007"),
    "hta":                  ("HTA",                     "execution",     "T1218.005"),
    "scr":                  ("Screen Saver",            "execution",     "T1546.002"),
    "lnk":                  ("Shortcut",                "execution",     "T1204.001"),
}

# ---------------------------------------------------------------------------
#  Concept patterns (regex/word lists) -> detection concept id
#  Each concept carries: logsource hints, sigma selection fields, yara terms,
#  mitre mapping and severity.
# ---------------------------------------------------------------------------
DETECTION_CONCEPTS = {
    "execution": {
        "label": "Process Execution",
        "words": ["execute", "executes", "executed", "run", "runs", "running", "launch",
                  "launches", "launched", "start", "starts", "started", "invoke",
                  "invokes", "spawn", "spawns", "spawned", "called", "call"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1059"],
        "severity": "high",
    },
    "powershell_execution": {
        "label": "PowerShell Activity",
        "words": ["powershell", "power shell", "pwsh"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1059.001"],
        "severity": "high",
    },
    "cmd_execution": {
        "label": "Command Prompt Activity",
        "words": ["cmd.exe", "command prompt", "cmd /c", "batch file", "command shell"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1059.003"],
        "severity": "medium",
    },
    "scheduled_task": {
        "label": "Scheduled Task Creation",
        "words": ["scheduled task", "schedule", "scheduler", "schtasks", "create task"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1053.005", "T1053"],
        "severity": "high",
    },
    "registry_modification": {
        "label": "Registry Modification",
        "words": ["registry", "reg add", "hkey", "hkcu", "hklm", "run key", "autostart",
                  "startup key", "persistence"],
        "logsource": {"category": "registry_set", "product": "windows"},
        "selection": ["TargetObject", "Details", "Image"],
        "mitre": ["T1547.001", "T1112"],
        "severity": "high",
    },
    "startup_persistence": {
        "label": "Startup Folder Persistence",
        "words": ["startup", "startup folder", "startup directory", "persistence",
                  "run key", "all users start"],
        "logsource": {"category": "file_event", "product": "windows"},
        "selection": ["TargetFilename", "Image"],
        "mitre": ["T1547.001"],
        "severity": "high",
    },
    "service_creation": {
        "label": "Service Installation",
        "words": ["service", "create service", "install service", "sc create", "auto start"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1543.003"],
        "severity": "high",
    },
    "credential_dumping": {
        "label": "Credential Dumping",
        "words": ["credential", "credentials", "password", "passwords", "hash",
                  "hashes", "ntlm", "lsass", "sam file", "dumping", "dump",
                  "mimikatz", "sekurlsa", "lsass.exe", "kerberos", "ticket"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1003", "T1003.001"],
        "severity": "critical",
    },
    "keylog": {
        "label": "Input Capture",
        "words": ["keylog", "key logger", "keystroke", "keystrokes", "typing", "input capture"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1056.001"],
        "severity": "high",
    },
    "network_connection": {
        "label": "Network Connection",
        "words": ["connect", "connects", "connecting", "connection", "beacon",
                  "beaconing", "callback", "phone home", "call home", "c2", "cnc",
                  "command and control", "command-and-control", "control server"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Initiated", "Image"],
        "mitre": ["T1071", "T1105"],
        "severity": "high",
    },
    "dns_query": {
        "label": "DNS Query",
        "words": ["dns", "resolve", "resolution", "resolving", "query"],
        "logsource": {"category": "dns_query", "product": "windows"},
        "selection": ["QueryName", "QueryType"],
        "mitre": ["T1568.002"],
        "severity": "medium",
    },
    "download": {
        "label": "File Download",
        "words": ["download", "downloads", "downloaded", "fetch", "fetches",
                  "fetched", "pull", "pull down", "retrieve", "retrieves"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Image"],
        "mitre": ["T1105"],
        "severity": "high",
    },
    "upload_exfiltration": {
        "label": "Upload / Exfiltration",
        "words": ["upload", "uploads", "uploaded", "exfil", "exfiltration",
                  "exfiltrate", "exfiltrates", "send the file", "data steal",
                  "steal data", "phish"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Image"],
        "mitre": ["T1041", "T1567"],
        "severity": "high",
    },
    "file_creation": {
        "label": "File Creation",
        "words": ["writes a file", "write file", "create a file", "creates a file",
                  "file created", "drop", "drops", "dropped", "drop file",
                  "save as", "saves", "save to", "write to disk"],
        "logsource": {"category": "file_event", "product": "windows"},
        "selection": ["TargetFilename", "Image"],
        "mitre": ["T1204.002"],
        "severity": "medium",
    },
    "file_event": {
        "label": "File Activity",
        "words": ["file", "files", "delete", "deletes", "deleted", "rename",
                  "renames", "renamed", "copy", "copies", "copied", "modify",
                  "modifies", "modified"],
        "logsource": {"category": "file_event", "product": "windows"},
        "selection": ["TargetFilename", "Image"],
        "mitre": ["T1204.002"],
        "severity": "medium",
    },
    "obfuscation": {
        "label": "Obfuscation / Encoding",
        "words": ["obfuscate", "obfuscated", "obfuscation", "base64", "encoded",
                  "encoding", "encrypted", "encrypt", "xor", "hexadecimal",
                  "base64-encoded", "compress", "compressed", "packer",
                  "anti-virus", "antivirus evasion", "stealth"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1027", "T1027.001"],
        "severity": "high",
    },
    "defense_disabling": {
        "label": "Defense Evasion (Disable AV / Logging)",
        "words": ["disable", "disables", "disabled", "for real-time protection",
                  "real-time protection", "windows defender", "turn off", "mimic",
                  "delete logs", "clear logs", "audit policy", "disable firewall",
                  "eset", "avast", "symantec", "defender", "antivirus"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1562.001"],
        "severity": "critical",
    },
    "lateral_movement": {
        "label": "Lateral Movement",
        "words": ["lateral movement", "scott", "connecting to another machine",
                  "connect to another", "remote desktop", "rdp", "winrm",
                  "wmi", "psexec", "admin share", "net use", "remote host"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Image"],
        "mitre": ["T1021.002"],
        "severity": "critical",
    },
    "recon_discovery": {
        "label": "Discovery / Reconnaissance",
        "words": ["recon", "reconnaissance", "enumerate", "enumeration",
                  "identify the hostname", "hostname", "users", "whoami",
                  "domain admins", "admin groups", "list of", "network scan",
                  "scanning", "probe", "unusual", "nmap", "discover"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1087", "T1033", "T1069"],
        "severity": "medium",
    },
    "data_destruction": {
        "label": "Data Destruction",
        "words": ["wipe", "wipes", "wiped", "destroy data", "delete the database",
                  "delete files", "delete all", "encrypt the disk", "format", "unmount"],
        "logsource": {"category": "file_event", "product": "windows"},
        "selection": ["TargetFilename", "Image"],
        "mitre": ["T1485"],
        "severity": "critical",
    },
    "impact": {
        "label": "Impact / Ransomware",
        "words": ["ransomware", "ransom", "lock screen", "encrypt files",
                  "encrypts files", "encrypt all", "bitlocker", "impact"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1486"],
        "severity": "critical",
    },
    "c2_beaconing": {
        "label": "C2 Beaconing",
        "words": ["beacon", "beaconing", "c2", "cnc", "command and control",
                  "callback", "heartbeat", "sleep timer", "cobalt strike"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Image"],
        "mitre": ["T1071.001"],
        "severity": "critical",
    },
    "http_request": {
        "label": "HTTP Request Activity",
        "words": ["http", "https", "uri", "url", "web request", "browser",
                  "internet explorer", "edge", "chrome", "firefox", "http request"],
        "logsource": {"category": "network_connection", "product": "windows"},
        "selection": ["DestinationIp", "DestinationPort", "Url", "Image"],
        "mitre": ["T1071.001"],
        "severity": "medium",
    },
    "phishing": {
        "label": "Phishing Delivery",
        "words": ["phish", "phishing", "spam", "malicious email", "email attachment",
                  "macro", "macro-laden", "office document", "word document",
                  "pdf attachment"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1566.001", "T1204"],
        "severity": "high",
    },
    "mutex_sync": {
        "label": "Mutex / Synchronization",
        "words": ["mutex", "global object", "named pipe", "named pipe", "pipe",
                  "semaphore", "sync object"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1010"],
        "severity": "medium",
    },
    "injection": {
        "label": "Process Injection",
        "words": ["inject", "injects", "injected", "injection", "dll injection",
                  "process hollowing", "hook", "hooking", "memory region", "write process memory"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1055"],
        "severity": "critical",
    },
    "scripting": {
        "label": "Script-Based Execution",
        "words": ["script", "scripts", "javascript", "vbscript", "vbs", "hta",
                  "macro", "macros", "wscript", "cscript", "jscript"],
        "logsource": {"category": "process_creation", "product": "windows"},
        "selection": ["Image", "CommandLine"],
        "mitre": ["T1059.005", "T1059.007"],
        "severity": "high",
    },
}

# ---------------------------------------------------------------------------
#  Sigma logsource presets used when concepts reference them
# ---------------------------------------------------------------------------
LOGSOURCE_PRESETS = {
    "default":             {"category": "process_creation", "product": "windows"},
    "process_creation":    {"category": "process_creation", "product": "windows"},
    "network_connection":  {"category": "network_connection", "product": "windows"},
    "dns_query":           {"category": "dns_query", "product": "windows"},
    "file_event":          {"category": "file_event", "product": "windows"},
    "registry_set":        {"category": "registry_set", "product": "windows"},
    "registry_add":        {"category": "registry_add", "product": "windows"},
    "process_access":      {"category": "process_access", "product": "windows"},
    "driver_load":         {"category": "driver_load", "product": "windows"},
    "powershell":          {"category": "ps_script", "product": "windows"},
    "image_load":          {"category": "image_load", "product": "windows"},
    "pipe_created":        {"category": "pipe_created", "product": "windows"},
    "firewall":            {"category": "firewall", "product": "windows"},
    "webserver":           {"category": "webserver", "product": "iis"},
}

# ---------------------------------------------------------------------------
#  MITRE ATT&CK full names for rendering
# ---------------------------------------------------------------------------
MITRE_NAMES = {
    "T1003":   "OS Credential Dumping",
    "T1003.001": "LSASS Memory",
    "T1003.003": "NTDS",
    "T1010":   "Application Window Discovery",
    "T1012":   "Query Registry",
    "T1016":   "System Network Configuration Discovery",
    "T1021.001": "Remote Desktop Protocol",
    "T1021.002": "SMB/Windows Admin Shares",
    "T1021.004": "SSH",
    "T1027":   "Obfuscated Files or Information",
    "T1027.001": "Binary Padding",
    "T1033":   "System Owner/User Discovery",
    "T1041":   "Exfiltration Over C2 Channel",
    "T1046":   "Network Service Scanning",
    "T1047":   "Windows Management Instrumentation",
    "T1048":   "Exfiltration Over Alternative Protocol",
    "T1053":   "Scheduled Task/Job",
    "T1053.002": "At (Windows)",
    "T1053.005": "Scheduled Task",
    "T1055":   "Process Injection",
    "T1056.001": "Keylogging",
    "T1057":   "Process Discovery",
    "T1059":   "Command and Scripting Interpreter",
    "T1059.001": "PowerShell",
    "T1059.003": "Windows Command Shell",
    "T1059.005": "Visual Basic",
    "T1059.006": "Python",
    "T1059.007": "JavaScript",
    "T1069":   "Permission Groups Discovery",
    "T1071":   "Application Layer Protocol",
    "T1071.001": "Web Protocols",
    "T1082":   "System Information Discovery",
    "T1087":   "Account Discovery",
    "T1105":   "Ingress Tool Transfer",
    "T1110":   "Brute Force",
    "T1112":   "Modify Registry",
    "T1127":   "Trusted Developer Utilities Proxy Execution",
    "T1127.001": "MSBuild",
    "T1140":   "Deobfuscate/Decode Files or Information",
    "T1187":   "Forced Authentication",
    "T1197":   "BITS Jobs",
    "T1204":   "User Execution",
    "T1204.001": "Malicious Link",
    "T1204.002": "Malicious File",
    "T1218":   "System Binary Proxy Execution",
    "T1218.005": "Mshta",
    "T1218.010": "Regsvr32",
    "T1218.011": "Rundll32",
    "T1221":   "Template Injection",
    "T1485":   "Data Destruction",
    "T1486":   "Data Encrypted for Impact",
    "T1490":   "Inhibit System Recovery",
    "T1543.003": "Windows Service",
    "T1546.002": "Screensaver",
    "T1547":   "Boot or Logon Autostart Execution",
    "T1547.001": "Registry Run Keys / Startup",
    "T1552":   "Unsecured Credentials",
    "T1555":   "Credentials from Password Stores",
    "T1560.001": "Archive via Utility",
    "T1562.001": "Disable or Modify Tools",
    "T1566":   "Phishing",
    "T1566.001": "Spearphishing Attachment",
    "T1567":   "Exfiltration Over Web Service",
    "T1568.002": "Domain Generation Algorithms",
}