import os
import time

import config
from database import get_connection

FORMAT_LABELS = {
    "pf": "PF (PF Sense blocklist)",
    "iptables": "iptables rules",
    "windows": "Windows Firewall / hosts",
    "hosts": "hosts file",
    "bind": "BIND zone",
    "domains": "plain domain list",
}


def fetch_blocklist_iocs(threshold_conf=0.5, types=None, feed_ids=None, days=config.IOC_EXPIRY_DAYS):
    """Fetch blocklistable IOCs from the DB within the given confidence threshold."""
    conn = get_connection()
    sql = """
        SELECT value, type, confidence, source_feed, severity
        FROM iocs
        WHERE blocklisted = 0
          AND confidence >= ?
          AND last_seen >= datetime('now', ?)
    """
    params = [threshold_conf, f"-{days} days"]
    if feed_ids:
        placeholders = ",".join("?" for _ in feed_ids)
        sql += f" AND feed_id IN ({placeholders})"
        params.extend(feed_ids)
    rows = conn.execute(sql, params).fetchall()
    conn.close()

    if not types:
        types = ["IP", "DOMAIN", "URL", "HASH"]
    return [r for r in rows if r["type"] in types]


def generate_blocklist(threshold_conf=0.5, types=None, fmt="pf", feed_ids=None):
    """Generate a blocklist artifact and persist metadata for the current run."""
    rows = fetch_blocklist_iocs(threshold_conf=threshold_conf, types=types, feed_ids=feed_ids)
    types = types or ["IP", "DOMAIN", "URL", "HASH"]
    counted_types = {t: 0 for t in types}
    lines = []
    seen = set()

    for r in rows:
        typ = r["type"]
        if typ not in counted_types:
            counted_types[typ] = 0
        value = r["value"].strip()
        if (typ, value) in seen:
            continue
        seen.add((typ, value))
        counted_types[typ] += 1
        rendered = _render_line(typ, value, fmt)
        if rendered:
            lines.append(rendered)

    os.makedirs(config.REPORT_DIR, exist_ok=True)
    ts = time.strftime("%Y%m%d%H%M%S")
    fname = f"blocklist_{fmt}_{ts}.txt"
    path = os.path.join(config.REPORT_DIR, fname)

    header = _header(fmt, len(seen), ts)
    payload = header + "\n".join(sorted(set(lines))) + "\n"

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(payload)

    conn = get_connection()
    conn.execute(
        """INSERT INTO blocklist_runs
           (generated_at, ioc_count, ip_count, domain_count, url_count, hash_count,
            blocklist_path, format, threshold_conf, auto_added)
           VALUES (datetime('now'), ?, ?, ?, ?, ?, ?, ?, ?, 0)""",
        (
            len(seen),
            counted_types.get("IP", 0),
            counted_types.get("DOMAIN", 0),
            counted_types.get("URL", 0),
            counted_types.get("HASH", 0),
            path,
            fmt,
            threshold_conf,
        ),
    )
    conn.commit()
    conn.close()
    return {
        "file": path,
        "filename": fname,
        "format": fmt,
        "total": len(seen),
        "by_type": counted_types,
        "generated_at": ts,
    }


def _header(fmt, count, ts):
    sep = "# " + "=" * 60
    if fmt == "pf":
        return f"{sep}\n# Generated by ThreatIntel-Aggregator\n# {ts}  |  {count} entries\n{sep}\n\n"
    if fmt == "iptables":
        return ""
    if fmt == "hosts":
        return "# Generated " + ts + "\n"
    return "# Generated by ThreatIntel-Aggregator " + ts + "\n"


def _render_line(typ, value, fmt):
    if fmt == "pf":
        if typ == "IP":
            return value
        if typ == "DOMAIN":
            return "domain:" + value
        if typ in ("URL",):
            return "url:" + value
        return None
    if fmt == "iptables":
        if typ == "IP":
            return f"-A INPUT -s {value} -j DROP"
        if typ == "DOMAIN":
            return f"-A OUTPUT -d {value} -j DROP"
        return None
    if fmt == "hosts":
        if typ in ("IP", "DOMAIN"):
            return f"0.0.0.0 {value}"
        return None
    if fmt == "bind":
        if typ == "DOMAIN":
            rel = value.rstrip(".")
            return f'zone "{rel}" {{ type master; file "null.zone"; }};'
        return None
    if fmt == "domains":
        if typ in ("DOMAIN", "IP"):
            return value
        return None
    return None