"""Zeek and Suricata signature generation.

Given a :class:`C2Profile`, these helpers emit:

* ``suricata/c2_beacons.rules``  — Suricata ``alert http`` rules that match the
  beacon's User-Agent, HTTP method and URI.
* ``zeek/c2_beacons.sig``        — Zeek ``signature`` definitions.
* ``zeek/beacon_detect.zeek``    — a Zeek event script example that models
  beacon interval / jitter timings (the *behavioral* companion to the purely
  content-based signatures).

Signature IDs are derived deterministically from the profile so rebuilt rules
stay stable across runs.
"""

from __future__ import annotations

import zlib

from .presets import C2Profile

SURICATA_SID_BASE = 525001
ZEEK_DEFAULT_PORTS = "80, 8080, 443, 8443"


def _sid(profile: C2Profile, slot: int) -> int:
    return SURICATA_SID_BASE + (zlib.crc32(profile.name.encode("utf-8")) % 90_000) + slot * 17


def _escaped_uri(uri: str) -> str:
    """Escape a URI for use inside Zeek regex payload / Suricata content."""
    return uri.replace("/", "\\/").replace(".", "\\.")


def build_suricata_rules(profile: C2Profile, ports: str = ZEEK_DEFAULT_PORTS) -> str:
    """Return a complete ``.rules`` file for the given profile."""
    sid = _sid(profile, 0)
    sid_generic = _sid(profile, 1)
    lines = []
    lines.append("#" + "=" * 78)
    lines.append(f"# Suricata rules — C2 beacon detection: {profile.name}")
    lines.append("# Generated by the C2 Detection Lab (auto-generated lab artifacts).")
    lines.append(
        "# Scope: experimental signatures for a closed lab environment. "
        "Validate before deployment."
    )
    lines.append("#" + "=" * 78)
    lines.append("")
    lines.append("# Base signature: fingerprints the unique beacon handshake.")
    lines.append("")
    lines.append("alert http $HOME_NET any -> $EXTERNAL_NET any (")
    lines.append(f'  msg:"C2-BEACON {profile.family} beaconing detected ({profile.name})";')
    lines.append("  flow:established,to_server;")
    lines.append(f'  http.method; content:"{profile.methods[0]}"; nocase;')
    lines.append(f'  http.user_agent; content:"{_escaped_uri(profile.user_agent[:64])}";')
    for uri in profile.uri_paths:
        lines.append(f'  http.uri; content:"{_escaped_uri(uri)}";')
    lines.append(f"  sid:{sid}; rev:1;")
    lines.append("  classtype:trojan-activity;")
    lines.append('  metadata:created_at 2026/01/01; reference:url,https://www.zeek.org;')
    lines.append(f'  metadata: profile "{profile.name}", family "{profile.family}";')
    lines.append(")")
    lines.append("")
    lines.append("# Tier-2 signature: any of the beacon URIs hit regardless of User-Agent.")
    lines.append("")
    lines.append("alert http $HOME_NET any -> $EXTERNAL_NET any (")
    lines.append(f'  msg:"C2-BEACON {profile.family} URI usage detected";')
    lines.append("  flow:established,to_server;")
    for uri in profile.uri_paths[:2]:
        lines.append(f'  http.uri; content:"{_escaped_uri(uri)}";')
    lines.append(f"  sid:{sid_generic}; rev:1;")
    lines.append("  classtype:trojan-activity;")
    lines.append('  metadata: created_at 2026/01/01;')
    lines.append(")")
    lines.append("")
    lines.append("# Suppression hint: high-interval beacons are expected in this lab.")
    lines.append(f"# threshold: type both, track by_src, count 5, seconds 120, sid {sid}")
    lines.append("")
    return "\n".join(lines)


def build_zeek_signatures(profile: C2Profile, ports: str = ZEEK_DEFAULT_PORTS) -> str:
    """Return a Zeek ``signatures`` file for the given profile."""
    lines = []
    lines.append("# Zeek signatures — C2 beacon detection: " + profile.name)
    lines.append("# Generated by the C2 Detection Lab. Drop into your signatures/")
    lines.append("# directory and enable via 'signatures' in your zeekctl config.")
    lines.append("")
    lines.append(f"signature c2-beacon-{profile.name.lower().replace(' ', '-')} {{")
    lines.append("    ip-proto = tcp")
    lines.append("    tcp-state established, originator")
    for uri in profile.uri_paths:
        lines.append(f"    payload /{_escaped_uri(uri)}/")
    lines.append("    ip-proto = tcp")
    lines.append(f'    event "{profile.family} C2 beacon pattern ({profile.name}) detected"')
    lines.append("}")
    lines.append("")
    lines.append("# Behavioural note: Zeek signatures match content only. Interval / jitter")
    lines.append("# detection requires the script companion beacon_detect.zeek.")
    lines.append("")
    return "\n".join(lines)


def build_zeek_script(profile: C2Profile, ports: str = ZEEK_DEFAULT_PORTS) -> str:
    """Return an example ``beacon_detect.zeek`` script modelling timings."""
    lines = []
    lines.append("// " + "=" * 78)
    lines.append("// Zeek script — beacon interval / jitter detection companion.")
    lines.append(f"// Profile: {profile.name}")
    lines.append("// Generated by the C2 Detection Lab.")
    lines.append("// Teaching skeleton that models beacon timing with SumStats.")
    lines.append("// " + "=" * 78)
    lines.append("")
    lines.append("module C2Beacon;")
    lines.append("")
    lines.append("export {")
    lines.append("    redef enum Log::ID += { LOG };")
    lines.append("    type Info: record {")
    lines.append("        ts:            time;")
    lines.append("        src_ip:        addr;")
    lines.append("        dst_ip:        addr;")
    lines.append("        interval_s:    double;")
    lines.append("        connections:   count;")
    lines.append("    };")
    lines.append("}")
    lines.append("")
    lines.append("redef record connection += { c2_beacon_ts: time &optional; }")
    lines.append("")
    lines.append("event new_connection(c: connection)")
    lines.append("    {")
    lines.append("    if ( c$id$orig_h != c$id$resp_h )")
    lines.append("        {")
    lines.append("        c$c2_beacon_ts = c$start_time;")
    lines.append("        local k = SumStats::Key($str=cat(c$id$orig_h));")
    lines.append("        SumStats::observe(\"beacon\", k, SumStats::Observation($dbl=interval_to_double(c$start_time - network_time())));")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("event zeek_init()")
    lines.append("    {")
    lines.append("    Log::create_stream(C2Beacon::LOG, [$columns=Info, $path=\"beacon\"]);")
    lines.append("    SumStats::create([$name=\"beacon\",")
    lines.append("        $reducers=set(SumStats::Sum($input_field=\"total\")),")
    lines.append("        $epoch=10min, $threshold=5,")
    lines.append("        $callback=finish_beacon]);")
    lines.append("    }")
    lines.append("")
    lines.append("global finish_beacon: function(s: SumStats::Result);")
    lines.append("")
    lines.append("function finish_beacon(s: SumStats::Result)")
    lines.append("    {")
    lines.append("    if ( s$reducers[\"beacon\"]$sum >= 5 )")
    lines.append("        {")
    lines.append("        NOTICE([$note=Note::Host_Beaconing,")
    lines.append("                $msg=fmt(\"Possible host beaconing (>=5 connections in epoch): %s\", s$key$str),")
    lines.append("                $src=to_addr(s$key$str)]);")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("// NOTE: teaching skeleton — a production beacon detector tracks")
    lines.append("// inter-arrival deltas and jitter (stddev/mean) per source, and")
    lines.append("// keys on dst_ip + UA hash, not just orig_h.")
    lines.append("")
    return "\n".join(lines)


def build_all_rules(profile: C2Profile) -> dict:
    """Convenience: all three artifacts keyed by file name."""
    return {
        "c2_beacons.rules": build_suricata_rules(profile),
        "c2_beacons.sig": build_zeek_signatures(profile),
        "beacon_detect.zeek": build_zeek_script(profile),
    }