"""Offline HTML report generator (zero external assets).

Report types:
  pack      - full pack: summary, severity distribution, per-rule XML listing.
  matrix    - stage x rule coverage matrix with MITRE ATT&CK mapping.
  severity  - rules grouped by severity bucket.
  single    - one rule addressed in detail.
"""
from __future__ import annotations

import html
import os
from datetime import datetime

from .rules_core import SEVERITY_BUCKETS, STAGES, STAGE_BY_KEY, RulePack, severity_bucket


def _esc(s: str) -> str:
    if s is None:
        return ""
    return html.escape(str(s), quote=True)


_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {
    --bg:#0f1420; --panel:#171d2c; --panel2:#1d2438; --line:#2a3350;
    --fg:#e6ebf5; --muted:#8a94ad; --accent:#4f8cff;
  }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--fg);
         font:14px/1.55 'Segoe UI', system-ui, sans-serif; }
  .wrap { max-width:1080px; margin:0 auto; padding:32px 24px 80px; }
  header { border-bottom:2px solid var(--line); padding-bottom:18px; margin-bottom:8px; }
  .kicker { color:var(--accent); text-transform:uppercase; letter-spacing:2.5px;
            font-size:11px; font-weight:700; }
  h1 { margin:6px 0 4px; font-size:26px; }
  .sub { color:var(--muted); }
  h2 { margin:34px 0 12px; color:var(--fg); font-size:19px;
       border-left:4px solid var(--accent); padding-left:10px; }
  .cards { display:flex; flex-wrap:wrap; gap:14px; margin:20px 0; }
  .card { flex:1 1 160px; background:var(--panel); border:1px solid var(--line);
          border-radius:12px; padding:16px 18px; }
  .card .n { font-size:30px; font-weight:800; }
  .card .l { color:var(--muted); font-size:12px; text-transform:uppercase;
             letter-spacing:1px; }
  table { width:100%; border-collapse:collapse; background:var(--panel);
          border:1px solid var(--line); border-radius:10px; overflow:hidden; }
  th { text-align:left; color:var(--muted); text-transform:uppercase;
       font-size:11px; letter-spacing:1px; padding:10px 12px;
       background:var(--panel2); }
  td { padding:10px 12px; border-top:1px solid var(--line); vertical-align:top; }
  tr:hover td { background:#20273c; }
  .chip { display:inline-block; padding:2px 9px; border-radius:20px;
          font-size:11px; font-weight:700; color:#fff; }
  .Llow { background:#7f8c8d; } .Lmed { background:#f39c12; }
  .Lhigh { background:#e67e22; } .Lcrit { background:#e74c3c; }
  .pill { display:inline-block; background:var(--panel2); border:1px solid var(--line);
          border-radius:8px; padding:4px 10px; margin-right:6px; font-size:12px; }
  pre { background:#0a0e18; border:1px solid var(--line); border-radius:8px;
        padding:14px; overflow-x:auto; font:12.5px/1.5 Consolas, monospace;
        color:#c8f0d0; }
  .bar { height:14px; border-radius:7px; background:var(--panel2); overflow:hidden;
         position:relative; }
  .bar > span { display:block; height:100%; }
  .barrow { display:flex; align-items:center; gap:12px; margin:8px 0; }
  .barrow .lbl { width:120px; color:var(--muted); font-size:12px; }
  .barrow .val { width:70px; text-align:right; font-size:12px; color:var(--muted); }
  .stage { background:var(--panel); border:1px solid var(--line); border-radius:10px;
           padding:12px 16px; margin:8px 0; display:flex; align-items:center;
           gap:14px; }
  .stage .dot { width:10px; height:10px; border-radius:50%; flex:0 0 10px; }
  .stage .sname { font-weight:700; width:230px; }
  .stage .tactic { color:var(--accent); font-size:12px; width:70px; }
  .stage .meta { color:var(--muted); font-size:12px; flex:1; }
  .ruleblk { background:var(--panel); border:1px solid var(--line);
             border-radius:12px; padding:16px; margin:14px 0; }
  .ruleblk h3 { margin:0 0 6px; font-size:15px; display:flex; gap:10px;
                align-items:center; }
  .muted { color:var(--muted); } .small { font-size:12px; }
  footer { margin-top:40px; color:var(--muted); font-size:11px;
           border-top:1px solid var(--line); padding-top:12px; }
</style>
</head>
<body>
<div class="wrap">
"""

_FOOT = """<footer>
  Generated by RulePackStudio &middot; {stamp} &middot; offline HTML report
  &mdash; no external resources loaded.
</footer>
</div>
</body>
</html>
"""


def _stamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _stat_card(n, label):
    return f'<div class="card"><div class="n">{n}</div><div class="l">{label}</div></div>'


def _severity_dist_html(pack: RulePack) -> str:
    counts = pack.count_by_severity()
    rows = []
    total = max(sum(counts.values()), 1)
    for b in SEVERITY_BUCKETS:
        v = counts.get(b["name"], 0)
        pct = round(v / total * 100)
        rows.append(
            f'<div class="barrow"><span class="lbl">{b["name"]}</span>'
            f'<div class="bar" style="flex:1">'
            f'<span style="width:{pct}%;background:{b["color"]}"></span></div>'
            f'<span class="val">{v} ({pct}%)</span></div>'
        )
    return "\n".join(rows)


def _stage_coverage_html(pack: RulePack) -> str:
    counts = pack.count_by_stage()
    out = []
    for st in STAGES:
        v = counts.get(st["key"], 0)
        dot = "#2ecc71" if v else "#3a4a7a"
        out.append(
            f'<div class="stage"><span class="dot" style="background:{dot}"></span>'
            f'<span class="sname">{_esc(st["name"])}</span>'
            f'<span class="tactic">{st["tactic"]}</span>'
            f'<span class="meta">{_esc(st["desc"])}</span>'
            f'<span style="font-weight:800">{v}</span></div>'
        )
    return "\n".join(out)


def _rule_block_html(rule) -> str:
    b = severity_bucket(rule.level)
    cls = {"Low": "low", "Medium": "med", "High": "high", "Critical": "crit"}.get(b["name"], "med")
    meta = [
        f'<span class="pill">{_esc(rule.stage_name)}</span>',
        f'<span class="pill">MITRE {_esc(rule["mitre"])}</span>',
        f'<span class="pill">src: {_esc(rule["log_source"])}</span>',
        f'<span class="pill">{_esc(rule["group"])}</span>',
    ]
    if not rule.get("enabled", True):
        meta.append('<span class="pill" style="color:#e74c3c">disabled</span>')
    return (
        f'<div class="ruleblk"><h3>'
        f'<span class="chip L{cls}">L{rule.level}</span>'
        f'<span>{rule.rid}</span></h3>'
        f'<p style="margin:4px 0 6px">{_esc(rule["description"])}</p>'
        f'<p class="small">{" ".join(meta)}</p>'
        f'<pre>{_esc(rule["xml"])}</pre></div>'
    )


def _coverage_matrix_html(pack: RulePack) -> str:
    rules = pack.enabled()
    all_ids = sorted(int(r["id"]) for r in rules)
    header = "<tr><th>Kill-chain stage</th><th>MITRE</th>"
    header += "".join(f"<th>{i:06d}</th>" for i in all_ids)
    header += "</tr>"
    rows = [header]
    for st in STAGES:
        stage_rules = [r for r in rules if r["stage"] == st["key"]]
        cells = []
        for i in all_ids:
            hit = next((r for r in stage_rules if int(r["id"]) == i), None)
            if hit:
                b = severity_bucket(hit.level)
                color = {"Low": "#7f8c8d", "Medium": "#f39c12",
                         "High": "#e67e22", "Critical": "#e74c3c"}.get(b["name"], "#7f8c8d")
                cells.append(f'<td style="color:{color};font-weight:800;text-align:center">&bull;</td>')
            else:
                cells.append('<td style="text-align:center;color:var(--line)">-</td>')
        rows.append(
            f'<tr><td style="font-weight:700">{_esc(st["name"])}</td>'
            f'<td>{st["tactic"]}</td>{"".join(cells)}</tr>'
        )
    return "<table>" + "\n".join(rows) + "</table>"


def _meta_banner(pack: RulePack) -> str:
    issues = pack.validate()
    return (
        '<div class="sub">' + _esc(f"{pack.name} v{pack.version}") + " &middot; "
        + _stat_row_meta(pack) + "</div>"
        + (f'<p class="small" style="color:#e74c3c">{len(issues)} validation issue(s) found.</p>'
           if issues else "")
    )


def _stat_row_meta(pack: RulePack) -> str:
    return (
        f"{pack.total} rules &middot; {pack.stages_covered}/{len(STAGES)} stages "
        f"&middot; avg level {pack.avg_level}"
    )


def _render(pack: RulePack, title: str, body: str) -> str:
    return _HEAD.replace("{title}", _esc(title)) + body + _FOOT.replace(
        "{stamp}", _stamp())


def generate_pack_report(pack: RulePack) -> str:
    body = [
        '<header><div class="kicker">Detection Engineering Report</div>'
        '<h1>Full Pack Report</h1>', _meta_banner(pack), "</header>",
        '<div class="cards">',
        _stat_card(pack.total, "Rules enabled"),
        _stat_card(pack.stages_covered, f"Stages of {len(STAGES)}"),
        _stat_card(pack.avg_level, "Average severity"),
        _stat_card(len(pack.rules) - pack.total, "Disabled"),
        "</div>",
        "<h2>Severity distribution</h2>", _severity_dist_html(pack),
        "<h2>Kill-chain coverage</h2>", _stage_coverage_html(pack),
        "<h2>Rules</h2>",
    ]
    rules = sorted(pack.enabled(),
                   key=lambda r: (STAGE_BY_KEY.get(r.stage, {}).get("name", ""), int(r["id"])))
    for r in rules:
        body.append(_rule_block_html(r))
    return _render(pack, "Full Pack Report - RulePackStudio", "".join(body))


def generate_matrix_report(pack: RulePack) -> str:
    body = [
        '<header><div class="kicker">Detection Engineering Report</div>'
        '<h1>Rule / Kill-chain Coverage Matrix</h1>', _meta_banner(pack), "</header>",
        _coverage_matrix_html(pack),
        "<h2>Stage detail</h2>", _stage_coverage_html(pack),
    ]
    return _render(pack, "Coverage Matrix - RulePackStudio", "".join(body))


def generate_severity_report(pack: RulePack) -> str:
    body = [
        '<header><div class="kicker">Detection Engineering Report</div>'
        '<h1>Severity Report</h1>', _meta_banner(pack), "</header>",
        "<h2>Distribution</h2>", _severity_dist_html(pack),
        "<h2>Rules by severity</h2>",
    ]
    for b in SEVERITY_BUCKETS:
        cls = {"Low": "low", "Medium": "med", "High": "high", "Critical": "crit"}[b["name"]]
        grp = [r for r in pack.enabled() if b["lo"] <= r.level <= b["hi"]]
        if not grp:
            continue
        body.append(f'<h3 style="color:var(--fg)"><span class="chip L{cls}">{b["name"]}</span> '
                    f'<span class="muted small">(levels {b["lo"]}-{b["hi"]})</span></h3>')
        for r in sorted(grp, key=lambda x: int(x["id"])):
            body.append(_rule_block_html(r))
    return _render(pack, "Severity Report - RulePackStudio", "".join(body))


def generate_single_rule_report(pack: RulePack, rid: int) -> str:
    rule = pack.get(rid)
    body = [
        '<header><div class="kicker">Detection Engineering Report</div>'
        f'<h1>Rule Detail &mdash; {rid:06d}</h1>',
        f'<div class="sub">{_esc(pack.name)} v{pack.version}</div></header>',
    ]
    if rule is None:
        body.append(f'<p class="muted">No rule with id {rid:06d}.</p>')
    else:
        body.append(_rule_block_html(rule))
        body.append("<h2>Context</h2>")
        body.append(
            f'<p>{_esc(rule["description"])}</p>'
            f'<p class="small">MITRE technique <b>{_esc(rule["mitre"])}</b> &middot; '
            f'stage <b>{_esc(rule.stage_name)}</b> &middot; log source '
            f'<b>{_esc(rule["log_source"])}</b></p>'
            f'<pre>{_esc(rule["xml"])}</pre>'
        )
    return _render(pack, f"Rule Detail {rid:06d} - RulePackStudio", "".join(body))


REPORT_TYPES = {
    "pack": ("Full Pack Report", generate_pack_report),
    "matrix": ("Coverage Matrix", generate_matrix_report),
    "severity": ("Severity Report", generate_severity_report),
    "single": ("Single Rule Report", generate_single_rule_report),
}


def generate_report(pack: RulePack, rtype: str, rid: int | None = None) -> str:
    if rtype == "single" and rid is not None:
        return generate_single_rule_report(pack, rid)
    name, fn = REPORT_TYPES[rtype]
    return fn(pack)


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path